In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_DIR = Path.cwd().parent

file_path = (
    PROJECT_DIR
    / "data"
    / "Final_Version"
    / "Raw"
    / "Approvals.csv"
)

print("File exists:", file_path.exists())

df = pd.read_csv(file_path)

pd.set_option("display.max.rows",None)
pd.set_option("display.max.columns",None)

df.sort_values("ApprovalID")
print("Rows saved:", len(df))

File exists: True
Rows saved: 90

In [2]:
df["ApprovalDate"]=pd.to_datetime(df["ApprovalDate"],
                                  format="mixed",
                                  dayfirst=True,
                                  errors="coerce")
df

    ApprovalID  FacilityID ApprovalDate ApprovedBy ApprovalStatus
0         5012        2037          NaT    Manager            NaN
1         5094        2049          NaT  Committee       Approved
2         5091        2175   2020-05-01  Committee       Rejected
3         5052        2142          NaT  Committee            NaN
4         5026        2027          NaT        NaN            NaN
5         5009        2170          NaT  Committee            NaN
6         5002        2115          NaT  Committee       Rejected
7         5096        2175   2020-05-01  Committee            NaN
8         5018        2149   2020-05-01    Manager            NaN
9         5191        2068          NaT    Manager            NaN
10        5049        2107          NaT        NaN       Approved
11        5130        2106   2021-12-05    Manager       approved
12        5135        2144   2021-12-05    Manager            NaN
13        5099        2050          NaT        NaN            NaN
14        5176        2067          NaT    Manager       Approved
15        5023        2049   2020-05-01  Committee            NaN
16        5047        2059          NaT        NaN       Approved
17        5051        2033          NaT  Committee       Rejected
18        5027        2008   2021-12-05    Manager       approved
19        5059        2188   2021-12-05    Manager       Rejected
20        5063        2015          NaT        NaN       approved
21        5153        2177   2020-05-01    Manager       Approved
22        5061        2001   2021-12-05        NaN       approved
23        5175        2155   2021-12-05    Manager       approved
24        5154        2066          NaT    Manager       approved
25        5180        2104   2020-05-01        NaN       Rejected
26        5021        2057   2021-12-05        NaN       Rejected
27        5196        2098   2020-05-01        NaN       Rejected
28        5123        2090          NaT        NaN       Rejected
29        5196        2106          NaT    Manager       approved
30        5071        2079   2021-12-05        NaN       Rejected
31        5190        2107   2021-12-05        NaN       Rejected
32        5118        2165   2020-05-01    Manager       Rejected
33        5015        2087          NaT    Manager       Approved
34        5082        2072          NaT        NaN       approved
35        5028        2027   2021-12-05    Manager            NaN
36        5188        2072   2021-12-05        NaN       Rejected
37        5061        2026          NaT    Manager            NaN
38        5045        2037          NaT    Manager       approved
39        5111        2190   2021-12-05    Manager       Approved
40        5085        2018   2021-12-05    Manager       Rejected
41        5020        2096          NaT        NaN       Approved
42        5163        2167          NaT        NaN       Approved
43        5169        2190          NaT        NaN       Rejected
44        5148        2030   2020-05-01        NaN       Rejected
45        5123        2033   2021-12-05    Manager            NaN
46        5081        2075          NaT        NaN       Approved
47        5108        2111          NaT  Committee            NaN
48        5104        2192          NaT  Committee       Approved
49        5033        2042   2021-12-05        NaN       Approved
50        5017        2033          NaT        NaN       approved
51        5051        2051   2020-05-01        NaN            NaN
52        5091        2174   2020-05-01  Committee       approved
53        5032        2006          NaT  Committee       Approved
54        5022        2076          NaT        NaN       Approved
55        5170        2024          NaT    Manager       Rejected
56        5075        2032          NaT    Manager       Rejected
57        5117        2183   2020-05-01  Committee            NaN
58        5105        2001          NaT    Manager       Rejected
59        5147        2064   2021-12-05    Manager       Approved
60        5148        2183   2021-12-05        NaN            NaN
61        5059        2122          NaT        NaN       Approved
62        5169        2015          NaT  Committee       Approved
63        5074        2093          NaT  Committee       Rejected
64        5167        2194   2021-12-05  Committee       Rejected
65        5081        2080          NaT        NaN       approved
66        5023        2106   2021-12-05  Committee            NaN
67        5152        2106          NaT    Manager            NaN
68        5007        2132          NaT  Committee       Rejected
69        5154        2038          NaT  Committee            NaN
70        5009        2168   2020-05-01        NaN       approved
71        5042        2197   2021-12-05        NaN       Approved
72        5121        2029   2021-12-05        NaN            NaN
73        5188        2163          NaT  Committee       Approved
74        5082        2163          NaT  Committee       approved
75        5025        2148   2021-12-05  Committee            NaN
76        5047        2074          NaT    Manager       Approved
77        5179        2094          NaT        NaN       Rejected
78        5145        2168   2021-12-05        NaN       Rejected
79        5020        2031   2021-12-05        NaN            NaN
80        5077        2165          NaT    Manager       Approved
81        5053        2184          NaT    Manager       approved
82        5036        2136   2020-05-01        NaN       Rejected
83        5169        2068          NaT  Committee       Approved
84        5123        2112          NaT        NaN       approved
85        5036        2010          NaT  Committee            NaN
86        5130        2186          NaT  Committee       approved
87        5083        2069          NaT  Committee       Approved
88        5013        2012   2021-12-05        NaN       Approved
89        5090        2159   2021-12-05  Committee       Rejected

In [3]:
df["ApprovalStatus"]=(df["ApprovalStatus"]
                      .str.strip()
                      .str.title())

df["ApprovedBy"]=(df["ApprovedBy"]
                      .str.strip()
                      .str.title())
df

    ApprovalID  FacilityID ApprovalDate ApprovedBy ApprovalStatus
0         5012        2037          NaT    Manager            NaN
1         5094        2049          NaT  Committee       Approved
2         5091        2175   2020-05-01  Committee       Rejected
3         5052        2142          NaT  Committee            NaN
4         5026        2027          NaT        NaN            NaN
5         5009        2170          NaT  Committee            NaN
6         5002        2115          NaT  Committee       Rejected
7         5096        2175   2020-05-01  Committee            NaN
8         5018        2149   2020-05-01    Manager            NaN
9         5191        2068          NaT    Manager            NaN
10        5049        2107          NaT        NaN       Approved
11        5130        2106   2021-12-05    Manager       Approved
12        5135        2144   2021-12-05    Manager            NaN
13        5099        2050          NaT        NaN            NaN
14        5176        2067          NaT    Manager       Approved
15        5023        2049   2020-05-01  Committee            NaN
16        5047        2059          NaT        NaN       Approved
17        5051        2033          NaT  Committee       Rejected
18        5027        2008   2021-12-05    Manager       Approved
19        5059        2188   2021-12-05    Manager       Rejected
20        5063        2015          NaT        NaN       Approved
21        5153        2177   2020-05-01    Manager       Approved
22        5061        2001   2021-12-05        NaN       Approved
23        5175        2155   2021-12-05    Manager       Approved
24        5154        2066          NaT    Manager       Approved
25        5180        2104   2020-05-01        NaN       Rejected
26        5021        2057   2021-12-05        NaN       Rejected
27        5196        2098   2020-05-01        NaN       Rejected
28        5123        2090          NaT        NaN       Rejected
29        5196        2106          NaT    Manager       Approved
30        5071        2079   2021-12-05        NaN       Rejected
31        5190        2107   2021-12-05        NaN       Rejected
32        5118        2165   2020-05-01    Manager       Rejected
33        5015        2087          NaT    Manager       Approved
34        5082        2072          NaT        NaN       Approved
35        5028        2027   2021-12-05    Manager            NaN
36        5188        2072   2021-12-05        NaN       Rejected
37        5061        2026          NaT    Manager            NaN
38        5045        2037          NaT    Manager       Approved
39        5111        2190   2021-12-05    Manager       Approved
40        5085        2018   2021-12-05    Manager       Rejected
41        5020        2096          NaT        NaN       Approved
42        5163        2167          NaT        NaN       Approved
43        5169        2190          NaT        NaN       Rejected
44        5148        2030   2020-05-01        NaN       Rejected
45        5123        2033   2021-12-05    Manager            NaN
46        5081        2075          NaT        NaN       Approved
47        5108        2111          NaT  Committee            NaN
48        5104        2192          NaT  Committee       Approved
49        5033        2042   2021-12-05        NaN       Approved
50        5017        2033          NaT        NaN       Approved
51        5051        2051   2020-05-01        NaN            NaN
52        5091        2174   2020-05-01  Committee       Approved
53        5032        2006          NaT  Committee       Approved
54        5022        2076          NaT        NaN       Approved
55        5170        2024          NaT    Manager       Rejected
56        5075        2032          NaT    Manager       Rejected
57        5117        2183   2020-05-01  Committee            NaN
58        5105        2001          NaT    Manager       Rejected
59        5147        2064   2021-12-05    Manager       Approved
60        5148        2183   2021-12-05        NaN            NaN
61        5059        2122          NaT        NaN       Approved
62        5169        2015          NaT  Committee       Approved
63        5074        2093          NaT  Committee       Rejected
64        5167        2194   2021-12-05  Committee       Rejected
65        5081        2080          NaT        NaN       Approved
66        5023        2106   2021-12-05  Committee            NaN
67        5152        2106          NaT    Manager            NaN
68        5007        2132          NaT  Committee       Rejected
69        5154        2038          NaT  Committee            NaN
70        5009        2168   2020-05-01        NaN       Approved
71        5042        2197   2021-12-05        NaN       Approved
72        5121        2029   2021-12-05        NaN            NaN
73        5188        2163          NaT  Committee       Approved
74        5082        2163          NaT  Committee       Approved
75        5025        2148   2021-12-05  Committee            NaN
76        5047        2074          NaT    Manager       Approved
77        5179        2094          NaT        NaN       Rejected
78        5145        2168   2021-12-05        NaN       Rejected
79        5020        2031   2021-12-05        NaN            NaN
80        5077        2165          NaT    Manager       Approved
81        5053        2184          NaT    Manager       Approved
82        5036        2136   2020-05-01        NaN       Rejected
83        5169        2068          NaT  Committee       Approved
84        5123        2112          NaT        NaN       Approved
85        5036        2010          NaT  Committee            NaN
86        5130        2186          NaT  Committee       Approved
87        5083        2069          NaT  Committee       Approved
88        5013        2012   2021-12-05        NaN       Approved
89        5090        2159   2021-12-05  Committee       Rejected

In [4]:
CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
output_file = CLEAN_DIR / "Facilities_Clean.csv"
df1=pd.read_csv(output_file)
df1

,FacilityID,CustomerID,FacilityType,AmountApproved,StartDate,TenorMonths,Customer_Exists
0,2002,1147,NaN,500000.0,NaN,18.5,True
1,2004,1038,Term Loan,10000.0,2021-01-01,24.0,False
2,2005,1027,Overdraft,500000.0,2021-01-15,NaN,False
3,2014,1077,Term Loan,NaN,NaN,24.0,True
4,2021,1080,Overdraft,NaN,NaN,18.5,False
5,2022,1102,NaN,NaN,NaN,12.0,True
6,2023,1120,Term Loan,NaN,NaN,12.0,True
7,2024,1103,Term Loan,NaN,2021-01-01,NaN,True
8,2028,1059,NaN,10000.0,NaN,12.0,False
9,2029,1040,Term Loan,10000.0,2021-01-01,18.5,False
10,2030,1064,Loan,NaN,2021-01-01,18.5,False
11,2031,1035,NaN,1500000.0,NaN,NaN,True
12,2032,1025,Term Loan,NaN,NaN,18.5,True
13,2033,1072,Term Loan,10000.0,NaN,NaN,True
14,2034,1110,Overdraft,NaN,NaN,18.5,False
15,2037,1119,NaN,NaN,NaN,24.0,False
16,2039,1117,Loan,NaN,2021-01-15,18.5,True
17,2047,1056,Term Loan,10000.0,2021-01-01,NaN,True
18,2048,1096,NaN,1500000.0,2021-01-01,18.5,False
19,2050,1043,Loan,500000.0,NaN,24.0,False
20,2054,1094,Overdraft,10000.0,2021-01-15,NaN,False
21,2055,1048,Loan,1500000.0,NaN,NaN,False
22,2057,1063,NaN,1500000.0,NaN,NaN,False
23,2058,1142,Loan,1500000.0,2021-01-15,18.5,True
24,2062,1096,Term Loan,10000.0,NaN,24.0,False
25,2064,1103,Loan,10000.0,NaN,12.0,True
26,2067,1138,Term Loan,NaN,2021-01-01,12.0,False
27,2072,1125,Term Loan,500000.0,2021-01-01,24.0,True
28,2075,1015,Loan,10000.0,2021-01-01,12.0,True
29,2083,1138,Term Loan,1500000.0,NaN,12.0,False
30,2084,1048,Overdraft,1500000.0,NaN,NaN,False
31,2085,1126,NaN,10000.0,NaN,24.0,True
32,2086,1074,Loan,NaN,2021-01-15,18.5,False
33,2091,1120,NaN,1500000.0,NaN,NaN,True
34,2093,1002,Term Loan,NaN,2021-01-01,18.5,False
35,2094,1028,NaN,10000.0,2021-01-01,12.0,True
36,2095,1145,Loan,NaN,NaN,NaN,False
37,2100,1030,Overdraft,1500000.0,NaN,24.0,True
38,2106,1087,Overdraft,10000.0,NaN,18.5,False
39,2108,1076,Loan,10000.0,2021-01-01,24.0,True
40,2111,1008,Term Loan,500000.0,NaN,NaN,False
41,2115,1091,NaN,NaN,NaN,18.5,False
42,2119,1128,Loan,500000.0,NaN,12.0,False
43,2120,1065,Term Loan,500000.0,2021-01-01,18.5,True
44,2121,1016,Loan,NaN,NaN,18.5,False
45,2127,1133,Term Loan,1500000.0,NaN,24.0,False
46,2130,1135,Loan,1500000.0,NaN,24.0,False
47,2133,1096,Loan,10000.0,2021-01-01,18.5,False
48,2144,1120,Term Loan,NaN,2021-01-01,NaN,True
49,2147,1080,Overdraft,1500000.0,2021-01-01,NaN,False
50,2149,1117,NaN,NaN,2021-01-01,18.5,True
51,2150,1124,NaN,1500000.0,2021-01-01,24.0,True
52,2153,1134,NaN,500000.0,NaN,18.5,True
53,2157,1036,Term Loan,10000.0,NaN,NaN,False
54,2159,1008,Loan,1500000.0,2021-01-01,NaN,False
55,2161,1007,Term Loan,1500000.0,2021-01-01,18.5,True
56,2163,1021,NaN,500000.0,2021-01-01,24.0,False
57,2165,1058,Loan,1500000.0,2021-01-01,18.5,False
58,2166,1063,Term Loan,500000.0,NaN,NaN,False
59,2168,1077,NaN,10000.0,NaN,24.0,True
60,2169,1034,NaN,NaN,NaN,18.5,False
61,2173,1146,NaN,NaN,NaN,18.5,True
62,2176,1049,Term Loan,500000.0,NaN,NaN,True
63,2183,1010,Overdraft,10000.0,2021-01-01,24.0,True
64,2184,1021,Overdraft,10000.0,2021-01-15,18.5,False
65,2185,1009,Overdraft,1500000.0,NaN,12.0,False
66,2186,1014,NaN,500000.0,NaN,NaN,True
67,2191,1124,Loan,10000.0,NaN,NaN,True
68,2192,1106,Term Loan,500000.0,2021-01-01,12.0,True
69,2193,1076,Overdraft,NaN,2021-01-01,18.5,True
70,2198,1092,NaN,1500000.0,2021-01-15,12.0,False

In [5]:
df[~df['FacilityID'].isin(df1['FacilityID'])]

df['Facilities_Exists']=df['FacilityID'].isin(df1['FacilityID'])
df

,ApprovalID,FacilityID,ApprovalDate,ApprovedBy,ApprovalStatus,Facilities_Exists
0,5012,2037,NaT,Manager,NaN,True
1,5094,2049,NaT,Committee,Approved,False
2,5091,2175,2020-05-01,Committee,Rejected,False
3,5052,2142,NaT,Committee,NaN,False
4,5026,2027,NaT,NaN,NaN,False
5,5009,2170,NaT,Committee,NaN,False
6,5002,2115,NaT,Committee,Rejected,True
7,5096,2175,2020-05-01,Committee,NaN,False
8,5018,2149,2020-05-01,Manager,NaN,True
9,5191,2068,NaT,Manager,NaN,False
10,5049,2107,NaT,NaN,Approved,False
11,5130,2106,2021-12-05,Manager,Approved,True
12,5135,2144,2021-12-05,Manager,NaN,True
13,5099,2050,NaT,NaN,NaN,True
14,5176,2067,NaT,Manager,Approved,True
15,5023,2049,2020-05-01,Committee,NaN,False
16,5047,2059,NaT,NaN,Approved,False
17,5051,2033,NaT,Committee,Rejected,True
18,5027,2008,2021-12-05,Manager,Approved,False
19,5059,2188,2021-12-05,Manager,Rejected,False
20,5063,2015,NaT,NaN,Approved,False
21,5153,2177,2020-05-01,Manager,Approved,False
22,5061,2001,2021-12-05,NaN,Approved,False
23,5175,2155,2021-12-05,Manager,Approved,False
24,5154,2066,NaT,Manager,Approved,False
25,5180,2104,2020-05-01,NaN,Rejected,False
26,5021,2057,2021-12-05,NaN,Rejected,True
27,5196,2098,2020-05-01,NaN,Rejected,False
28,5123,2090,NaT,NaN,Rejected,False
29,5196,2106,NaT,Manager,Approved,True
30,5071,2079,2021-12-05,NaN,Rejected,False
31,5190,2107,2021-12-05,NaN,Rejected,False
32,5118,2165,2020-05-01,Manager,Rejected,True
33,5015,2087,NaT,Manager,Approved,False
34,5082,2072,NaT,NaN,Approved,True
35,5028,2027,2021-12-05,Manager,NaN,False
36,5188,2072,2021-12-05,NaN,Rejected,True
37,5061,2026,NaT,Manager,NaN,False
38,5045,2037,NaT,Manager,Approved,True
39,5111,2190,2021-12-05,Manager,Approved,False
40,5085,2018,2021-12-05,Manager,Rejected,False
41,5020,2096,NaT,NaN,Approved,False
42,5163,2167,NaT,NaN,Approved,False
43,5169,2190,NaT,NaN,Rejected,False
44,5148,2030,2020-05-01,NaN,Rejected,True
45,5123,2033,2021-12-05,Manager,NaN,True
46,5081,2075,NaT,NaN,Approved,True
47,5108,2111,NaT,Committee,NaN,True
48,5104,2192,NaT,Committee,Approved,True
49,5033,2042,2021-12-05,NaN,Approved,False
50,5017,2033,NaT,NaN,Approved,True
51,5051,2051,2020-05-01,NaN,NaN,False
52,5091,2174,2020-05-01,Committee,Approved,False
53,5032,2006,NaT,Committee,Approved,False
54,5022,2076,NaT,NaN,Approved,False
55,5170,2024,NaT,Manager,Rejected,True
56,5075,2032,NaT,Manager,Rejected,True
57,5117,2183,2020-05-01,Committee,NaN,True
58,5105,2001,NaT,Manager,Rejected,False
59,5147,2064,2021-12-05,Manager,Approved,True
60,5148,2183,2021-12-05,NaN,NaN,True
61,5059,2122,NaT,NaN,Approved,False
62,5169,2015,NaT,Committee,Approved,False
63,5074,2093,NaT,Committee,Rejected,True
64,5167,2194,2021-12-05,Committee,Rejected,False
65,5081,2080,NaT,NaN,Approved,False
66,5023,2106,2021-12-05,Committee,NaN,True
67,5152,2106,NaT,Manager,NaN,True
68,5007,2132,NaT,Committee,Rejected,False
69,5154,2038,NaT,Committee,NaN,False
70,5009,2168,2020-05-01,NaN,Approved,True
71,5042,2197,2021-12-05,NaN,Approved,False
72,5121,2029,2021-12-05,NaN,NaN,True
73,5188,2163,NaT,Committee,Approved,True
74,5082,2163,NaT,Committee,Approved,True
75,5025,2148,2021-12-05,Committee,NaN,False
76,5047,2074,NaT,Manager,Approved,False
77,5179,2094,NaT,NaN,Rejected,True
78,5145,2168,2021-12-05,NaN,Rejected,True
79,5020,2031,2021-12-05,NaN,NaN,True
80,5077,2165,NaT,Manager,Approved,True
81,5053,2184,NaT,Manager,Approved,True
82,5036,2136,2020-05-01,NaN,Rejected,False
83,5169,2068,NaT,Committee,Approved,False
84,5123,2112,NaT,NaN,Approved,False
85,5036,2010,NaT,Committee,NaN,False
86,5130,2186,NaT,Committee,Approved,True
87,5083,2069,NaT,Committee,Approved,False
88,5013,2012,2021-12-05,NaN,Approved,False
89,5090,2159,2021-12-05,Committee,Rejected,True

In [6]:

duplicates = df[df.duplicated("ApprovalID", keep=False)] \
            .sort_values("ApprovalID")
duplicates

#df.to_csv(r"C:\Users\Madhura J\Desktop\Data Analyst Banking Project\data\validation\Approvals_duplicates.csv",index=False)


#need to check because it has kind of same values - 5023
#df["ApprovalID"].is_unique

,ApprovalID,FacilityID,ApprovalDate,ApprovedBy,ApprovalStatus,Facilities_Exists
5,5009,2170,NaT,Committee,NaN,False
70,5009,2168,2020-05-01,NaN,Approved,True
41,5020,2096,NaT,NaN,Approved,False
79,5020,2031,2021-12-05,NaN,NaN,True
66,5023,2106,2021-12-05,Committee,NaN,True
15,5023,2049,2020-05-01,Committee,NaN,False
82,5036,2136,2020-05-01,NaN,Rejected,False
85,5036,2010,NaT,Committee,NaN,False
16,5047,2059,NaT,NaN,Approved,False
76,5047,2074,NaT,Manager,Approved,False
51,5051,2051,2020-05-01,NaN,NaN,False
17,5051,2033,NaT,Committee,Rejected,True
61,5059,2122,NaT,NaN,Approved,False
19,5059,2188,2021-12-05,Manager,Rejected,False
22,5061,2001,2021-12-05,NaN,Approved,False
37,5061,2026,NaT,Manager,NaN,False
46,5081,2075,NaT,NaN,Approved,True
65,5081,2080,NaT,NaN,Approved,False
74,5082,2163,NaT,Committee,Approved,True
34,5082,2072,NaT,NaN,Approved,True
2,5091,2175,2020-05-01,Committee,Rejected,False
52,5091,2174,2020-05-01,Committee,Approved,False
28,5123,2090,NaT,NaN,Rejected,False
45,5123,2033,2021-12-05,Manager,NaN,True
84,5123,2112,NaT,NaN,Approved,False
11,5130,2106,2021-12-05,Manager,Approved,True
86,5130,2186,NaT,Committee,Approved,True
44,5148,2030,2020-05-01,NaN,Rejected,True
60,5148,2183,2021-12-05,NaN,NaN,True
69,5154,2038,NaT,Committee,NaN,False
24,5154,2066,NaT,Manager,Approved,False
62,5169,2015,NaT,Committee,Approved,False
43,5169,2190,NaT,NaN,Rejected,False
83,5169,2068,NaT,Committee,Approved,False
73,5188,2163,NaT,Committee,Approved,True
36,5188,2072,2021-12-05,NaN,Rejected,True
29,5196,2106,NaT,Manager,Approved,True
27,5196,2098,2020-05-01,NaN,Rejected,False

In [7]:
df["DuplicateApprovalID_Exists"]=df.duplicated(subset="ApprovalID",keep=False)
df

,ApprovalID,FacilityID,ApprovalDate,ApprovedBy,ApprovalStatus,Facilities_Exists,DuplicateApprovalID_Exists
0,5012,2037,NaT,Manager,NaN,True,False
1,5094,2049,NaT,Committee,Approved,False,False
2,5091,2175,2020-05-01,Committee,Rejected,False,True
3,5052,2142,NaT,Committee,NaN,False,False
4,5026,2027,NaT,NaN,NaN,False,False
5,5009,2170,NaT,Committee,NaN,False,True
6,5002,2115,NaT,Committee,Rejected,True,False
7,5096,2175,2020-05-01,Committee,NaN,False,False
8,5018,2149,2020-05-01,Manager,NaN,True,False
9,5191,2068,NaT,Manager,NaN,False,False
10,5049,2107,NaT,NaN,Approved,False,False
11,5130,2106,2021-12-05,Manager,Approved,True,True
12,5135,2144,2021-12-05,Manager,NaN,True,False
13,5099,2050,NaT,NaN,NaN,True,False
14,5176,2067,NaT,Manager,Approved,True,False
15,5023,2049,2020-05-01,Committee,NaN,False,True
16,5047,2059,NaT,NaN,Approved,False,True
17,5051,2033,NaT,Committee,Rejected,True,True
18,5027,2008,2021-12-05,Manager,Approved,False,False
19,5059,2188,2021-12-05,Manager,Rejected,False,True
20,5063,2015,NaT,NaN,Approved,False,False
21,5153,2177,2020-05-01,Manager,Approved,False,False
22,5061,2001,2021-12-05,NaN,Approved,False,True
23,5175,2155,2021-12-05,Manager,Approved,False,False
24,5154,2066,NaT,Manager,Approved,False,True
25,5180,2104,2020-05-01,NaN,Rejected,False,False
26,5021,2057,2021-12-05,NaN,Rejected,True,False
27,5196,2098,2020-05-01,NaN,Rejected,False,True
28,5123,2090,NaT,NaN,Rejected,False,True
29,5196,2106,NaT,Manager,Approved,True,True
30,5071,2079,2021-12-05,NaN,Rejected,False,False
31,5190,2107,2021-12-05,NaN,Rejected,False,False
32,5118,2165,2020-05-01,Manager,Rejected,True,False
33,5015,2087,NaT,Manager,Approved,False,False
34,5082,2072,NaT,NaN,Approved,True,True
35,5028,2027,2021-12-05,Manager,NaN,False,False
36,5188,2072,2021-12-05,NaN,Rejected,True,True
37,5061,2026,NaT,Manager,NaN,False,True
38,5045,2037,NaT,Manager,Approved,True,False
39,5111,2190,2021-12-05,Manager,Approved,False,False
40,5085,2018,2021-12-05,Manager,Rejected,False,False
41,5020,2096,NaT,NaN,Approved,False,True
42,5163,2167,NaT,NaN,Approved,False,False
43,5169,2190,NaT,NaN,Rejected,False,True
44,5148,2030,2020-05-01,NaN,Rejected,True,True
45,5123,2033,2021-12-05,Manager,NaN,True,True
46,5081,2075,NaT,NaN,Approved,True,True
47,5108,2111,NaT,Committee,NaN,True,False
48,5104,2192,NaT,Committee,Approved,True,False
49,5033,2042,2021-12-05,NaN,Approved,False,False
50,5017,2033,NaT,NaN,Approved,True,False
51,5051,2051,2020-05-01,NaN,NaN,False,True
52,5091,2174,2020-05-01,Committee,Approved,False,True
53,5032,2006,NaT,Committee,Approved,False,False
54,5022,2076,NaT,NaN,Approved,False,False
55,5170,2024,NaT,Manager,Rejected,True,False
56,5075,2032,NaT,Manager,Rejected,True,False
57,5117,2183,2020-05-01,Committee,NaN,True,False
58,5105,2001,NaT,Manager,Rejected,False,False
59,5147,2064,2021-12-05,Manager,Approved,True,False
60,5148,2183,2021-12-05,NaN,NaN,True,True
61,5059,2122,NaT,NaN,Approved,False,True
62,5169,2015,NaT,Committee,Approved,False,True
63,5074,2093,NaT,Committee,Rejected,True,False
64,5167,2194,2021-12-05,Committee,Rejected,False,False
65,5081,2080,NaT,NaN,Approved,False,True
66,5023,2106,2021-12-05,Committee,NaN,True,True
67,5152,2106,NaT,Manager,NaN,True,False
68,5007,2132,NaT,Committee,Rejected,False,False
69,5154,2038,NaT,Committee,NaN,False,True
70,5009,2168,2020-05-01,NaN,Approved,True,True
71,5042,2197,2021-12-05,NaN,Approved,False,False
72,5121,2029,2021-12-05,NaN,NaN,True,False
73,5188,2163,NaT,Committee,Approved,True,True
74,5082,2163,NaT,Committee,Approved,True,True
75,5025,2148,2021-12-05,Committee,NaN,False,False
76,5047,2074,NaT,Manager,Approved,False,True
77,5179,2094,NaT,NaN,Rejected,True,False
78,5145,2168,2021-12-05,NaN,Rejected,True,False
79,5020,2031,2021-12-05,NaN,NaN,True,True
80,5077,2165,NaT,Manager,Approved,True,False
81,5053,2184,NaT,Manager,Approved,True,False
82,5036,2136,2020-05-01,NaN,Rejected,False,True
83,5169,2068,NaT,Committee,Approved,False,True
84,5123,2112,NaT,NaN,Approved,False,True
85,5036,2010,NaT,Committee,NaN,False,True
86,5130,2186,NaT,Committee,Approved,True,True
87,5083,2069,NaT,Committee,Approved,False,False
88,5013,2012,2021-12-05,NaN,Approved,False,False
89,5090,2159,2021-12-05,Committee,Rejected,True,False

In [8]:
PROJECT_DIR = Path.cwd().parent

CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

output_file = CLEAN_DIR / "Approvals_Clean.csv"

df.to_csv(output_file, index=False)

print("Saved successfully:", output_file)
print("Rows saved:", len(df))

Saved successfully: C:\Users\Madhura J\Desktop\Data Analyst Banking Project\data\Final_Version\Clean\Approvals_Clean.csv
Rows saved: 90