In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_DIR = Path.cwd().parent

file_path = (
    PROJECT_DIR
    / "data"
    / "Final_Version"
    / "Raw"
    / "Collaterals.csv"
)

print("File exists:", file_path.exists())

df = pd.read_csv(file_path)

CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
output_file = CLEAN_DIR / "Facilities_Clean.csv"

print("File exists:", output_file.exists())

df2 = pd.read_csv(output_file)
print("Rows saved:", len(df2))


pd.set_option("display.max.rows",None)
pd.set_option("display.max.columns",None)

df.sort_values("CollateralID")
print("Rows saved:", len(df))

File exists: True
File exists: True
Rows saved: 71
Rows saved: 90

In [2]:
df["CollateralID"].is_unique

False

In [3]:
df["DuplicateExists"]=df.duplicated(subset="CollateralID",keep=False)
df

    CollateralID  FacilityID CollateralType  CollateralValue  DuplicateExists
0           4156        2018           Cash         -10000.0             True
1           4103        2002       Property         -10000.0             True
2           4186        2186            NaN         900000.0             True
3           4087        2038       Property              NaN            False
4           4028        2163      Guarantee              NaN             True
5           4008        2007            NaN         900000.0            False
6           4187        2031      Guarantee              NaN            False
7           4191        2023      Guarantee         -10000.0            False
8           4148        2141           Cash         -10000.0            False
9           4021        2124       Property              NaN            False
10          4059        2095      Guarantee         300000.0            False
11          4009        2049            NaN              NaN            False
12          4011        2018       Property              NaN             True
13          4049        2114            NaN              NaN             True
14          4114        2046           Cash              NaN            False
15          4014        2118      Guarantee         900000.0            False
16          4196        2137       Property         900000.0            False
17          4091        2170      Guarantee              NaN            False
18          4053        2099       Property         -10000.0            False
19          4103        2001           Cash         300000.0             True
20          4158        2056      Guarantee         900000.0            False
21          4063        2170       Property         900000.0            False
22          4010        2107           Cash              NaN             True
23          4011        2124      Guarantee         900000.0             True
24          4170        2092       Property         900000.0            False
25          4023        2033           Cash         900000.0             True
26          4127        2179           Cash              NaN            False
27          4077        2154      Guarantee         300000.0            False
28          4155        2199            NaN         300000.0            False
29          4013        2171            NaN         300000.0            False
30          4179        2058       Property         -10000.0            False
31          4139        2051       Property              NaN            False
32          4090        2050       Property         -10000.0            False
33          4042        2183      Guarantee         300000.0            False
34          4195        2111       Property         300000.0            False
35          4061        2091       Property         900000.0            False
36          4098        2193            NaN         900000.0             True
37          4079        2121            NaN         -10000.0            False
38          4046        2181            NaN         900000.0             True
39          4083        2196           Cash              NaN             True
40          4031        2016      Guarantee         900000.0            False
41          4001        2072      Guarantee         900000.0             True
42          4058        2147       Property              NaN            False
43          4023        2162      Guarantee         -10000.0             True
44          4083        2030      Guarantee              NaN             True
45          4172        2064           Cash         -10000.0             True
46          4033        2110            NaN         -10000.0            False
47          4001        2160      Guarantee              NaN             True
48          4023        2023      Guarantee              NaN             True
49          4102        2120      Guarantee              NaN            False
50          4055        2059            NaN         -10000.0            False
51          4098        2044      Guarantee         -10000.0             True
52          4006        2103           Cash         300000.0            False
53          4067        2083            NaN              NaN             True
54          4082        2127      Guarantee              NaN            False
55          4086        2064            NaN         900000.0            False
56          4110        2164       Property              NaN            False
57          4156        2016           Cash         -10000.0             True
58          4093        2172            NaN         300000.0            False
59          4168        2006      Guarantee         300000.0            False
60          4106        2147            NaN         -10000.0            False
61          4052        2069       Property         -10000.0            False
62          4046        2077       Property         -10000.0             True
63          4065        2004            NaN         -10000.0            False
64          4119        2140           Cash         900000.0            False
65          4049        2033      Guarantee         300000.0             True
66          4182        2132           Cash         -10000.0            False
67          4096        2145           Cash         300000.0            False
68          4172        2169            NaN         -10000.0             True
69          4136        2141       Property              NaN            False
70          4067        2060            NaN         300000.0             True
71          4046        2147            NaN         -10000.0             True
72          4149        2165      Guarantee         300000.0            False
73          4066        2064           Cash         900000.0            False
74          4050        2025       Property              NaN            False
75          4186        2178      Guarantee         300000.0             True
76          4097        2030           Cash         300000.0            False
77          4010        2119       Property         300000.0             True
78          4099        2048           Cash         -10000.0            False
79          4092        2026            NaN         900000.0            False
80          4172        2155           Cash              NaN             True
81          4142        2029       Property         900000.0            False
82          4039        2134      Guarantee         -10000.0            False
83          4030        2138       Property         -10000.0            False
84          4121        2012            NaN         -10000.0            False
85          4010        2035            NaN         300000.0             True
86          4064        2159            NaN         900000.0            False
87          4028        2101            NaN         300000.0             True
88          4005        2025       Property         -10000.0            False
89          4183        2198       Property              NaN            False

In [4]:
df3=df["CollateralValue"]<0
df["NegativeValueExists"]=df["CollateralValue"]<0
df

,CollateralID,FacilityID,CollateralType,CollateralValue,DuplicateExists,NegativeValueExists
0,4156,2018,Cash,-10000.0,True,True
1,4103,2002,Property,-10000.0,True,True
2,4186,2186,NaN,900000.0,True,False
3,4087,2038,Property,NaN,False,False
4,4028,2163,Guarantee,NaN,True,False
5,4008,2007,NaN,900000.0,False,False
6,4187,2031,Guarantee,NaN,False,False
7,4191,2023,Guarantee,-10000.0,False,True
8,4148,2141,Cash,-10000.0,False,True
9,4021,2124,Property,NaN,False,False
10,4059,2095,Guarantee,300000.0,False,False
11,4009,2049,NaN,NaN,False,False
12,4011,2018,Property,NaN,True,False
13,4049,2114,NaN,NaN,True,False
14,4114,2046,Cash,NaN,False,False
15,4014,2118,Guarantee,900000.0,False,False
16,4196,2137,Property,900000.0,False,False
17,4091,2170,Guarantee,NaN,False,False
18,4053,2099,Property,-10000.0,False,True
19,4103,2001,Cash,300000.0,True,False
20,4158,2056,Guarantee,900000.0,False,False
21,4063,2170,Property,900000.0,False,False
22,4010,2107,Cash,NaN,True,False
23,4011,2124,Guarantee,900000.0,True,False
24,4170,2092,Property,900000.0,False,False
25,4023,2033,Cash,900000.0,True,False
26,4127,2179,Cash,NaN,False,False
27,4077,2154,Guarantee,300000.0,False,False
28,4155,2199,NaN,300000.0,False,False
29,4013,2171,NaN,300000.0,False,False
30,4179,2058,Property,-10000.0,False,True
31,4139,2051,Property,NaN,False,False
32,4090,2050,Property,-10000.0,False,True
33,4042,2183,Guarantee,300000.0,False,False
34,4195,2111,Property,300000.0,False,False
35,4061,2091,Property,900000.0,False,False
36,4098,2193,NaN,900000.0,True,False
37,4079,2121,NaN,-10000.0,False,True
38,4046,2181,NaN,900000.0,True,False
39,4083,2196,Cash,NaN,True,False
40,4031,2016,Guarantee,900000.0,False,False
41,4001,2072,Guarantee,900000.0,True,False
42,4058,2147,Property,NaN,False,False
43,4023,2162,Guarantee,-10000.0,True,True
44,4083,2030,Guarantee,NaN,True,False
45,4172,2064,Cash,-10000.0,True,True
46,4033,2110,NaN,-10000.0,False,True
47,4001,2160,Guarantee,NaN,True,False
48,4023,2023,Guarantee,NaN,True,False
49,4102,2120,Guarantee,NaN,False,False
50,4055,2059,NaN,-10000.0,False,True
51,4098,2044,Guarantee,-10000.0,True,True
52,4006,2103,Cash,300000.0,False,False
53,4067,2083,NaN,NaN,True,False
54,4082,2127,Guarantee,NaN,False,False
55,4086,2064,NaN,900000.0,False,False
56,4110,2164,Property,NaN,False,False
57,4156,2016,Cash,-10000.0,True,True
58,4093,2172,NaN,300000.0,False,False
59,4168,2006,Guarantee,300000.0,False,False
60,4106,2147,NaN,-10000.0,False,True
61,4052,2069,Property,-10000.0,False,True
62,4046,2077,Property,-10000.0,True,True
63,4065,2004,NaN,-10000.0,False,True
64,4119,2140,Cash,900000.0,False,False
65,4049,2033,Guarantee,300000.0,True,False
66,4182,2132,Cash,-10000.0,False,True
67,4096,2145,Cash,300000.0,False,False
68,4172,2169,NaN,-10000.0,True,True
69,4136,2141,Property,NaN,False,False
70,4067,2060,NaN,300000.0,True,False
71,4046,2147,NaN,-10000.0,True,True
72,4149,2165,Guarantee,300000.0,False,False
73,4066,2064,Cash,900000.0,False,False
74,4050,2025,Property,NaN,False,False
75,4186,2178,Guarantee,300000.0,True,False
76,4097,2030,Cash,300000.0,False,False
77,4010,2119,Property,300000.0,True,False
78,4099,2048,Cash,-10000.0,False,True
79,4092,2026,NaN,900000.0,False,False
80,4172,2155,Cash,NaN,True,False
81,4142,2029,Property,900000.0,False,False
82,4039,2134,Guarantee,-10000.0,False,True
83,4030,2138,Property,-10000.0,False,True
84,4121,2012,NaN,-10000.0,False,True
85,4010,2035,NaN,300000.0,True,False
86,4064,2159,NaN,900000.0,False,False
87,4028,2101,NaN,300000.0,True,False
88,4005,2025,Property,-10000.0,False,True
89,4183,2198,Property,NaN,False,False

In [5]:

df["CollateralType"]=(df["CollateralType"]
                      .str.strip()
                      .str.title())
df

,CollateralID,FacilityID,CollateralType,CollateralValue,DuplicateExists,NegativeValueExists
0,4156,2018,Cash,-10000.0,True,True
1,4103,2002,Property,-10000.0,True,True
2,4186,2186,NaN,900000.0,True,False
3,4087,2038,Property,NaN,False,False
4,4028,2163,Guarantee,NaN,True,False
5,4008,2007,NaN,900000.0,False,False
6,4187,2031,Guarantee,NaN,False,False
7,4191,2023,Guarantee,-10000.0,False,True
8,4148,2141,Cash,-10000.0,False,True
9,4021,2124,Property,NaN,False,False
10,4059,2095,Guarantee,300000.0,False,False
11,4009,2049,NaN,NaN,False,False
12,4011,2018,Property,NaN,True,False
13,4049,2114,NaN,NaN,True,False
14,4114,2046,Cash,NaN,False,False
15,4014,2118,Guarantee,900000.0,False,False
16,4196,2137,Property,900000.0,False,False
17,4091,2170,Guarantee,NaN,False,False
18,4053,2099,Property,-10000.0,False,True
19,4103,2001,Cash,300000.0,True,False
20,4158,2056,Guarantee,900000.0,False,False
21,4063,2170,Property,900000.0,False,False
22,4010,2107,Cash,NaN,True,False
23,4011,2124,Guarantee,900000.0,True,False
24,4170,2092,Property,900000.0,False,False
25,4023,2033,Cash,900000.0,True,False
26,4127,2179,Cash,NaN,False,False
27,4077,2154,Guarantee,300000.0,False,False
28,4155,2199,NaN,300000.0,False,False
29,4013,2171,NaN,300000.0,False,False
30,4179,2058,Property,-10000.0,False,True
31,4139,2051,Property,NaN,False,False
32,4090,2050,Property,-10000.0,False,True
33,4042,2183,Guarantee,300000.0,False,False
34,4195,2111,Property,300000.0,False,False
35,4061,2091,Property,900000.0,False,False
36,4098,2193,NaN,900000.0,True,False
37,4079,2121,NaN,-10000.0,False,True
38,4046,2181,NaN,900000.0,True,False
39,4083,2196,Cash,NaN,True,False
40,4031,2016,Guarantee,900000.0,False,False
41,4001,2072,Guarantee,900000.0,True,False
42,4058,2147,Property,NaN,False,False
43,4023,2162,Guarantee,-10000.0,True,True
44,4083,2030,Guarantee,NaN,True,False
45,4172,2064,Cash,-10000.0,True,True
46,4033,2110,NaN,-10000.0,False,True
47,4001,2160,Guarantee,NaN,True,False
48,4023,2023,Guarantee,NaN,True,False
49,4102,2120,Guarantee,NaN,False,False
50,4055,2059,NaN,-10000.0,False,True
51,4098,2044,Guarantee,-10000.0,True,True
52,4006,2103,Cash,300000.0,False,False
53,4067,2083,NaN,NaN,True,False
54,4082,2127,Guarantee,NaN,False,False
55,4086,2064,NaN,900000.0,False,False
56,4110,2164,Property,NaN,False,False
57,4156,2016,Cash,-10000.0,True,True
58,4093,2172,NaN,300000.0,False,False
59,4168,2006,Guarantee,300000.0,False,False
60,4106,2147,NaN,-10000.0,False,True
61,4052,2069,Property,-10000.0,False,True
62,4046,2077,Property,-10000.0,True,True
63,4065,2004,NaN,-10000.0,False,True
64,4119,2140,Cash,900000.0,False,False
65,4049,2033,Guarantee,300000.0,True,False
66,4182,2132,Cash,-10000.0,False,True
67,4096,2145,Cash,300000.0,False,False
68,4172,2169,NaN,-10000.0,True,True
69,4136,2141,Property,NaN,False,False
70,4067,2060,NaN,300000.0,True,False
71,4046,2147,NaN,-10000.0,True,True
72,4149,2165,Guarantee,300000.0,False,False
73,4066,2064,Cash,900000.0,False,False
74,4050,2025,Property,NaN,False,False
75,4186,2178,Guarantee,300000.0,True,False
76,4097,2030,Cash,300000.0,False,False
77,4010,2119,Property,300000.0,True,False
78,4099,2048,Cash,-10000.0,False,True
79,4092,2026,NaN,900000.0,False,False
80,4172,2155,Cash,NaN,True,False
81,4142,2029,Property,900000.0,False,False
82,4039,2134,Guarantee,-10000.0,False,True
83,4030,2138,Property,-10000.0,False,True
84,4121,2012,NaN,-10000.0,False,True
85,4010,2035,NaN,300000.0,True,False
86,4064,2159,NaN,900000.0,False,False
87,4028,2101,NaN,300000.0,True,False
88,4005,2025,Property,-10000.0,False,True
89,4183,2198,Property,NaN,False,False

In [6]:
df["FacilityIDExists"]=df["FacilityID"].isin(df2["FacilityID"])
df

,CollateralID,FacilityID,CollateralType,CollateralValue,DuplicateExists,NegativeValueExists,FacilityIDExists
0,4156,2018,Cash,-10000.0,True,True,False
1,4103,2002,Property,-10000.0,True,True,True
2,4186,2186,NaN,900000.0,True,False,True
3,4087,2038,Property,NaN,False,False,False
4,4028,2163,Guarantee,NaN,True,False,True
5,4008,2007,NaN,900000.0,False,False,False
6,4187,2031,Guarantee,NaN,False,False,True
7,4191,2023,Guarantee,-10000.0,False,True,True
8,4148,2141,Cash,-10000.0,False,True,False
9,4021,2124,Property,NaN,False,False,False
10,4059,2095,Guarantee,300000.0,False,False,True
11,4009,2049,NaN,NaN,False,False,False
12,4011,2018,Property,NaN,True,False,False
13,4049,2114,NaN,NaN,True,False,False
14,4114,2046,Cash,NaN,False,False,False
15,4014,2118,Guarantee,900000.0,False,False,False
16,4196,2137,Property,900000.0,False,False,False
17,4091,2170,Guarantee,NaN,False,False,False
18,4053,2099,Property,-10000.0,False,True,False
19,4103,2001,Cash,300000.0,True,False,False
20,4158,2056,Guarantee,900000.0,False,False,False
21,4063,2170,Property,900000.0,False,False,False
22,4010,2107,Cash,NaN,True,False,False
23,4011,2124,Guarantee,900000.0,True,False,False
24,4170,2092,Property,900000.0,False,False,False
25,4023,2033,Cash,900000.0,True,False,True
26,4127,2179,Cash,NaN,False,False,False
27,4077,2154,Guarantee,300000.0,False,False,False
28,4155,2199,NaN,300000.0,False,False,False
29,4013,2171,NaN,300000.0,False,False,False
30,4179,2058,Property,-10000.0,False,True,True
31,4139,2051,Property,NaN,False,False,False
32,4090,2050,Property,-10000.0,False,True,True
33,4042,2183,Guarantee,300000.0,False,False,True
34,4195,2111,Property,300000.0,False,False,True
35,4061,2091,Property,900000.0,False,False,True
36,4098,2193,NaN,900000.0,True,False,True
37,4079,2121,NaN,-10000.0,False,True,True
38,4046,2181,NaN,900000.0,True,False,False
39,4083,2196,Cash,NaN,True,False,False
40,4031,2016,Guarantee,900000.0,False,False,False
41,4001,2072,Guarantee,900000.0,True,False,True
42,4058,2147,Property,NaN,False,False,True
43,4023,2162,Guarantee,-10000.0,True,True,False
44,4083,2030,Guarantee,NaN,True,False,True
45,4172,2064,Cash,-10000.0,True,True,True
46,4033,2110,NaN,-10000.0,False,True,False
47,4001,2160,Guarantee,NaN,True,False,False
48,4023,2023,Guarantee,NaN,True,False,True
49,4102,2120,Guarantee,NaN,False,False,True
50,4055,2059,NaN,-10000.0,False,True,False
51,4098,2044,Guarantee,-10000.0,True,True,False
52,4006,2103,Cash,300000.0,False,False,False
53,4067,2083,NaN,NaN,True,False,True
54,4082,2127,Guarantee,NaN,False,False,True
55,4086,2064,NaN,900000.0,False,False,True
56,4110,2164,Property,NaN,False,False,False
57,4156,2016,Cash,-10000.0,True,True,False
58,4093,2172,NaN,300000.0,False,False,False
59,4168,2006,Guarantee,300000.0,False,False,False
60,4106,2147,NaN,-10000.0,False,True,True
61,4052,2069,Property,-10000.0,False,True,False
62,4046,2077,Property,-10000.0,True,True,False
63,4065,2004,NaN,-10000.0,False,True,True
64,4119,2140,Cash,900000.0,False,False,False
65,4049,2033,Guarantee,300000.0,True,False,True
66,4182,2132,Cash,-10000.0,False,True,False
67,4096,2145,Cash,300000.0,False,False,False
68,4172,2169,NaN,-10000.0,True,True,True
69,4136,2141,Property,NaN,False,False,False
70,4067,2060,NaN,300000.0,True,False,False
71,4046,2147,NaN,-10000.0,True,True,True
72,4149,2165,Guarantee,300000.0,False,False,True
73,4066,2064,Cash,900000.0,False,False,True
74,4050,2025,Property,NaN,False,False,False
75,4186,2178,Guarantee,300000.0,True,False,False
76,4097,2030,Cash,300000.0,False,False,True
77,4010,2119,Property,300000.0,True,False,True
78,4099,2048,Cash,-10000.0,False,True,True
79,4092,2026,NaN,900000.0,False,False,False
80,4172,2155,Cash,NaN,True,False,False
81,4142,2029,Property,900000.0,False,False,True
82,4039,2134,Guarantee,-10000.0,False,True,False
83,4030,2138,Property,-10000.0,False,True,False
84,4121,2012,NaN,-10000.0,False,True,False
85,4010,2035,NaN,300000.0,True,False,False
86,4064,2159,NaN,900000.0,False,False,True
87,4028,2101,NaN,300000.0,True,False,False
88,4005,2025,Property,-10000.0,False,True,False
89,4183,2198,Property,NaN,False,False,True

In [7]:
PROJECT_DIR = Path.cwd().parent

CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

output_file = CLEAN_DIR / "Collaterals_Clean.csv"

df.to_csv(output_file, index=False)

print("Saved successfully:", output_file)
print("Rows saved:", len(df))

Saved successfully: C:\Users\Madhura J\Desktop\Data Analyst Banking Project\data\Final_Version\Clean\Collaterals_Clean.csv
Rows saved: 90