In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_DIR = Path.cwd().parent

file_path = (
    PROJECT_DIR
    / "data"
    / "Final_Version"
    / "Raw"
    / "CovenantChecks.csv"
)

print("File exists:", file_path.exists())
df = pd.read_csv(file_path)

CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
output_file = CLEAN_DIR / "Facilities_Clean.csv"

print("File exists:", output_file.exists())
df2 = pd.read_csv(output_file)

pd.set_option("display.max.rows",None)
pd.set_option("display.max.columns",None)

df.sort_values("CovenantID")
print("Rows saved:", len(df))

File exists: True
File exists: True
Rows saved: 90

In [2]:
df3=df.duplicated(subset="CovenantID",keep=False)
df3
df["DuplicateExistsFlag"]=df.duplicated(subset="CovenantID",keep=False)
df

,CovenantID,FacilityID,CovenantType,Threshold,LastCheckedDate,DuplicateExistsFlag
0,6101,2085,DSCR,bad,NaN,False
1,6110,2079,LTV,1.2,NaN,False
2,6049,2109,DSCR,1.2,2021-03-01,False
3,6100,2147,DSCR,bad,NaN,False
4,6059,2117,LTV,1.2,2021-03-01,False
5,6137,2052,LTV,bad,NaN,False
6,6159,2066,LTV,bad,NaN,False
7,6130,2150,NaN,1.5,2021-03-01,True
8,6001,2041,NaN,1.2,NaN,True
9,6198,2101,DSCR,NaN,NaN,False
10,6005,2108,LTV,1.5,NaN,False
11,6199,2150,DSCR,1.5,01/02/2022,False
12,6007,2143,DSCR,1.5,2021-03-01,True
13,6103,2093,DSCR,1.2,NaN,False
14,6022,2062,LTV,1.5,NaN,False
15,6019,2074,NaN,1.5,NaN,True
16,6136,2082,NaN,bad,NaN,True
17,6145,2044,LTV,bad,2021-03-01,False
18,6024,2125,NaN,NaN,NaN,False
19,6195,2042,DSCR,bad,2021-03-01,False
20,6064,2130,NaN,bad,NaN,True
21,6064,2150,NaN,1.5,NaN,True
22,6060,2192,DSCR,1.5,NaN,False
23,6092,2024,LTV,bad,NaN,False
24,6036,2152,NaN,1.5,2021-03-01,False
25,6085,2018,LTV,bad,2021-03-01,False
26,6042,2068,NaN,1.5,01/02/2022,False
27,6011,2036,NaN,NaN,NaN,True
28,6074,2033,LTV,bad,2021-03-01,False
29,6134,2035,DSCR,1.2,NaN,False
30,6152,2009,LTV,NaN,2021-03-01,False
31,6071,2164,DSCR,bad,01/02/2022,False
32,6065,2013,LTV,1.2,2021-03-01,True
33,6157,2080,LTV,1.2,01/02/2022,False
34,6136,2140,LTV,1.5,01/02/2022,True
35,6166,2198,DSCR,1.2,2021-03-01,False
36,6181,2170,DSCR,1.5,NaN,False
37,6164,2028,NaN,1.5,NaN,True
38,6187,2197,DSCR,1.2,NaN,False
39,6083,2131,DSCR,NaN,01/02/2022,False
40,6079,2036,NaN,NaN,NaN,False
41,6064,2090,DSCR,bad,NaN,True
42,6047,2183,LTV,NaN,NaN,False
43,6150,2079,DSCR,bad,01/02/2022,False
44,6143,2037,DSCR,bad,NaN,False
45,6160,2175,LTV,bad,NaN,False
46,6034,2190,LTV,1.5,2021-03-01,True
47,6098,2195,DSCR,NaN,01/02/2022,False
48,6045,2191,DSCR,bad,NaN,False
49,6178,2174,DSCR,1.5,2021-03-01,False
50,6054,2091,LTV,1.5,01/02/2022,True
51,6029,2039,NaN,1.5,NaN,False
52,6114,2123,DSCR,NaN,2021-03-01,False
53,6175,2044,DSCR,bad,01/02/2022,False
54,6183,2095,LTV,1.5,2021-03-01,False
55,6020,2131,LTV,bad,NaN,True
56,6065,2189,DSCR,bad,2021-03-01,True
57,6031,2058,DSCR,bad,NaN,False
58,6062,2051,LTV,1.5,2021-03-01,False
59,6107,2147,LTV,NaN,NaN,False
60,6056,2002,LTV,bad,NaN,False
61,6014,2113,DSCR,bad,NaN,False
62,6102,2149,NaN,bad,NaN,False
63,6011,2110,LTV,NaN,2021-03-01,True
64,6046,2077,LTV,bad,NaN,False
65,6001,2165,DSCR,NaN,NaN,True
66,6018,2074,NaN,bad,NaN,False
67,6087,2142,NaN,bad,NaN,False
68,6170,2093,DSCR,1.5,NaN,False
69,6155,2006,NaN,bad,01/02/2022,False
70,6020,2106,NaN,1.2,2021-03-01,True
71,6007,2010,DSCR,bad,2021-03-01,True
72,6068,2186,NaN,NaN,01/02/2022,False
73,6130,2120,DSCR,1.2,NaN,True
74,6149,2075,DSCR,bad,NaN,False
75,6164,2097,DSCR,1.2,01/02/2022,True
76,6069,2124,LTV,NaN,2021-03-01,False
77,6034,2052,LTV,NaN,NaN,True
78,6006,2058,LTV,1.5,NaN,False
79,6030,2084,DSCR,bad,NaN,False
80,6013,2052,DSCR,1.5,NaN,False
81,6172,2151,NaN,1.2,NaN,False
82,6054,2021,NaN,1.5,NaN,True
83,6164,2165,NaN,NaN,01/02/2022,True
84,6111,2070,DSCR,1.5,NaN,False
85,6108,2112,NaN,1.5,01/02/2022,False
86,6091,2032,NaN,NaN,2021-03-01,False
87,6164,2077,LTV,bad,01/02/2022,True
88,6009,2151,DSCR,NaN,2021-03-01,False
89,6019,2054,NaN,1.5,2021-03-01,True

In [3]:
df["FacilityExistsFlag"]=df["FacilityID"].isin(df2["FacilityID"])
df

,CovenantID,FacilityID,CovenantType,Threshold,LastCheckedDate,DuplicateExistsFlag,FacilityExistsFlag
0,6101,2085,DSCR,bad,NaN,False,True
1,6110,2079,LTV,1.2,NaN,False,False
2,6049,2109,DSCR,1.2,2021-03-01,False,False
3,6100,2147,DSCR,bad,NaN,False,True
4,6059,2117,LTV,1.2,2021-03-01,False,False
5,6137,2052,LTV,bad,NaN,False,False
6,6159,2066,LTV,bad,NaN,False,False
7,6130,2150,NaN,1.5,2021-03-01,True,True
8,6001,2041,NaN,1.2,NaN,True,False
9,6198,2101,DSCR,NaN,NaN,False,False
10,6005,2108,LTV,1.5,NaN,False,True
11,6199,2150,DSCR,1.5,01/02/2022,False,True
12,6007,2143,DSCR,1.5,2021-03-01,True,False
13,6103,2093,DSCR,1.2,NaN,False,True
14,6022,2062,LTV,1.5,NaN,False,True
15,6019,2074,NaN,1.5,NaN,True,False
16,6136,2082,NaN,bad,NaN,True,False
17,6145,2044,LTV,bad,2021-03-01,False,False
18,6024,2125,NaN,NaN,NaN,False,False
19,6195,2042,DSCR,bad,2021-03-01,False,False
20,6064,2130,NaN,bad,NaN,True,True
21,6064,2150,NaN,1.5,NaN,True,True
22,6060,2192,DSCR,1.5,NaN,False,True
23,6092,2024,LTV,bad,NaN,False,True
24,6036,2152,NaN,1.5,2021-03-01,False,False
25,6085,2018,LTV,bad,2021-03-01,False,False
26,6042,2068,NaN,1.5,01/02/2022,False,False
27,6011,2036,NaN,NaN,NaN,True,False
28,6074,2033,LTV,bad,2021-03-01,False,True
29,6134,2035,DSCR,1.2,NaN,False,False
30,6152,2009,LTV,NaN,2021-03-01,False,False
31,6071,2164,DSCR,bad,01/02/2022,False,False
32,6065,2013,LTV,1.2,2021-03-01,True,False
33,6157,2080,LTV,1.2,01/02/2022,False,False
34,6136,2140,LTV,1.5,01/02/2022,True,False
35,6166,2198,DSCR,1.2,2021-03-01,False,True
36,6181,2170,DSCR,1.5,NaN,False,False
37,6164,2028,NaN,1.5,NaN,True,True
38,6187,2197,DSCR,1.2,NaN,False,False
39,6083,2131,DSCR,NaN,01/02/2022,False,False
40,6079,2036,NaN,NaN,NaN,False,False
41,6064,2090,DSCR,bad,NaN,True,False
42,6047,2183,LTV,NaN,NaN,False,True
43,6150,2079,DSCR,bad,01/02/2022,False,False
44,6143,2037,DSCR,bad,NaN,False,True
45,6160,2175,LTV,bad,NaN,False,False
46,6034,2190,LTV,1.5,2021-03-01,True,False
47,6098,2195,DSCR,NaN,01/02/2022,False,False
48,6045,2191,DSCR,bad,NaN,False,True
49,6178,2174,DSCR,1.5,2021-03-01,False,False
50,6054,2091,LTV,1.5,01/02/2022,True,True
51,6029,2039,NaN,1.5,NaN,False,True
52,6114,2123,DSCR,NaN,2021-03-01,False,False
53,6175,2044,DSCR,bad,01/02/2022,False,False
54,6183,2095,LTV,1.5,2021-03-01,False,True
55,6020,2131,LTV,bad,NaN,True,False
56,6065,2189,DSCR,bad,2021-03-01,True,False
57,6031,2058,DSCR,bad,NaN,False,True
58,6062,2051,LTV,1.5,2021-03-01,False,False
59,6107,2147,LTV,NaN,NaN,False,True
60,6056,2002,LTV,bad,NaN,False,True
61,6014,2113,DSCR,bad,NaN,False,False
62,6102,2149,NaN,bad,NaN,False,True
63,6011,2110,LTV,NaN,2021-03-01,True,False
64,6046,2077,LTV,bad,NaN,False,False
65,6001,2165,DSCR,NaN,NaN,True,True
66,6018,2074,NaN,bad,NaN,False,False
67,6087,2142,NaN,bad,NaN,False,False
68,6170,2093,DSCR,1.5,NaN,False,True
69,6155,2006,NaN,bad,01/02/2022,False,False
70,6020,2106,NaN,1.2,2021-03-01,True,True
71,6007,2010,DSCR,bad,2021-03-01,True,False
72,6068,2186,NaN,NaN,01/02/2022,False,True
73,6130,2120,DSCR,1.2,NaN,True,True
74,6149,2075,DSCR,bad,NaN,False,True
75,6164,2097,DSCR,1.2,01/02/2022,True,False
76,6069,2124,LTV,NaN,2021-03-01,False,False
77,6034,2052,LTV,NaN,NaN,True,False
78,6006,2058,LTV,1.5,NaN,False,True
79,6030,2084,DSCR,bad,NaN,False,True
80,6013,2052,DSCR,1.5,NaN,False,False
81,6172,2151,NaN,1.2,NaN,False,False
82,6054,2021,NaN,1.5,NaN,True,True
83,6164,2165,NaN,NaN,01/02/2022,True,True
84,6111,2070,DSCR,1.5,NaN,False,False
85,6108,2112,NaN,1.5,01/02/2022,False,False
86,6091,2032,NaN,NaN,2021-03-01,False,True
87,6164,2077,LTV,bad,01/02/2022,True,False
88,6009,2151,DSCR,NaN,2021-03-01,False,False
89,6019,2054,NaN,1.5,2021-03-01,True,True

In [4]:
df['LastCheckedDate']=pd.to_datetime(df['LastCheckedDate'],
format="mixed",
dayfirst=True,
errors="coerce")
df

,CovenantID,FacilityID,CovenantType,Threshold,LastCheckedDate,DuplicateExistsFlag,FacilityExistsFlag
0,6101,2085,DSCR,bad,NaT,False,True
1,6110,2079,LTV,1.2,NaT,False,False
2,6049,2109,DSCR,1.2,2021-03-01,False,False
3,6100,2147,DSCR,bad,NaT,False,True
4,6059,2117,LTV,1.2,2021-03-01,False,False
5,6137,2052,LTV,bad,NaT,False,False
6,6159,2066,LTV,bad,NaT,False,False
7,6130,2150,NaN,1.5,2021-03-01,True,True
8,6001,2041,NaN,1.2,NaT,True,False
9,6198,2101,DSCR,NaN,NaT,False,False
10,6005,2108,LTV,1.5,NaT,False,True
11,6199,2150,DSCR,1.5,2022-02-01,False,True
12,6007,2143,DSCR,1.5,2021-03-01,True,False
13,6103,2093,DSCR,1.2,NaT,False,True
14,6022,2062,LTV,1.5,NaT,False,True
15,6019,2074,NaN,1.5,NaT,True,False
16,6136,2082,NaN,bad,NaT,True,False
17,6145,2044,LTV,bad,2021-03-01,False,False
18,6024,2125,NaN,NaN,NaT,False,False
19,6195,2042,DSCR,bad,2021-03-01,False,False
20,6064,2130,NaN,bad,NaT,True,True
21,6064,2150,NaN,1.5,NaT,True,True
22,6060,2192,DSCR,1.5,NaT,False,True
23,6092,2024,LTV,bad,NaT,False,True
24,6036,2152,NaN,1.5,2021-03-01,False,False
25,6085,2018,LTV,bad,2021-03-01,False,False
26,6042,2068,NaN,1.5,2022-02-01,False,False
27,6011,2036,NaN,NaN,NaT,True,False
28,6074,2033,LTV,bad,2021-03-01,False,True
29,6134,2035,DSCR,1.2,NaT,False,False
30,6152,2009,LTV,NaN,2021-03-01,False,False
31,6071,2164,DSCR,bad,2022-02-01,False,False
32,6065,2013,LTV,1.2,2021-03-01,True,False
33,6157,2080,LTV,1.2,2022-02-01,False,False
34,6136,2140,LTV,1.5,2022-02-01,True,False
35,6166,2198,DSCR,1.2,2021-03-01,False,True
36,6181,2170,DSCR,1.5,NaT,False,False
37,6164,2028,NaN,1.5,NaT,True,True
38,6187,2197,DSCR,1.2,NaT,False,False
39,6083,2131,DSCR,NaN,2022-02-01,False,False
40,6079,2036,NaN,NaN,NaT,False,False
41,6064,2090,DSCR,bad,NaT,True,False
42,6047,2183,LTV,NaN,NaT,False,True
43,6150,2079,DSCR,bad,2022-02-01,False,False
44,6143,2037,DSCR,bad,NaT,False,True
45,6160,2175,LTV,bad,NaT,False,False
46,6034,2190,LTV,1.5,2021-03-01,True,False
47,6098,2195,DSCR,NaN,2022-02-01,False,False
48,6045,2191,DSCR,bad,NaT,False,True
49,6178,2174,DSCR,1.5,2021-03-01,False,False
50,6054,2091,LTV,1.5,2022-02-01,True,True
51,6029,2039,NaN,1.5,NaT,False,True
52,6114,2123,DSCR,NaN,2021-03-01,False,False
53,6175,2044,DSCR,bad,2022-02-01,False,False
54,6183,2095,LTV,1.5,2021-03-01,False,True
55,6020,2131,LTV,bad,NaT,True,False
56,6065,2189,DSCR,bad,2021-03-01,True,False
57,6031,2058,DSCR,bad,NaT,False,True
58,6062,2051,LTV,1.5,2021-03-01,False,False
59,6107,2147,LTV,NaN,NaT,False,True
60,6056,2002,LTV,bad,NaT,False,True
61,6014,2113,DSCR,bad,NaT,False,False
62,6102,2149,NaN,bad,NaT,False,True
63,6011,2110,LTV,NaN,2021-03-01,True,False
64,6046,2077,LTV,bad,NaT,False,False
65,6001,2165,DSCR,NaN,NaT,True,True
66,6018,2074,NaN,bad,NaT,False,False
67,6087,2142,NaN,bad,NaT,False,False
68,6170,2093,DSCR,1.5,NaT,False,True
69,6155,2006,NaN,bad,2022-02-01,False,False
70,6020,2106,NaN,1.2,2021-03-01,True,True
71,6007,2010,DSCR,bad,2021-03-01,True,False
72,6068,2186,NaN,NaN,2022-02-01,False,True
73,6130,2120,DSCR,1.2,NaT,True,True
74,6149,2075,DSCR,bad,NaT,False,True
75,6164,2097,DSCR,1.2,2022-02-01,True,False
76,6069,2124,LTV,NaN,2021-03-01,False,False
77,6034,2052,LTV,NaN,NaT,True,False
78,6006,2058,LTV,1.5,NaT,False,True
79,6030,2084,DSCR,bad,NaT,False,True
80,6013,2052,DSCR,1.5,NaT,False,False
81,6172,2151,NaN,1.2,NaT,False,False
82,6054,2021,NaN,1.5,NaT,True,True
83,6164,2165,NaN,NaN,2022-02-01,True,True
84,6111,2070,DSCR,1.5,NaT,False,False
85,6108,2112,NaN,1.5,2022-02-01,False,False
86,6091,2032,NaN,NaN,2021-03-01,False,True
87,6164,2077,LTV,bad,2022-02-01,True,False
88,6009,2151,DSCR,NaN,2021-03-01,False,False
89,6019,2054,NaN,1.5,2021-03-01,True,True

In [5]:
df["Threshold"]=pd.to_numeric(df["Threshold"],errors="coerce")
df

,CovenantID,FacilityID,CovenantType,Threshold,LastCheckedDate,DuplicateExistsFlag,FacilityExistsFlag
0,6101,2085,DSCR,NaN,NaT,False,True
1,6110,2079,LTV,1.2,NaT,False,False
2,6049,2109,DSCR,1.2,2021-03-01,False,False
3,6100,2147,DSCR,NaN,NaT,False,True
4,6059,2117,LTV,1.2,2021-03-01,False,False
5,6137,2052,LTV,NaN,NaT,False,False
6,6159,2066,LTV,NaN,NaT,False,False
7,6130,2150,NaN,1.5,2021-03-01,True,True
8,6001,2041,NaN,1.2,NaT,True,False
9,6198,2101,DSCR,NaN,NaT,False,False
10,6005,2108,LTV,1.5,NaT,False,True
11,6199,2150,DSCR,1.5,2022-02-01,False,True
12,6007,2143,DSCR,1.5,2021-03-01,True,False
13,6103,2093,DSCR,1.2,NaT,False,True
14,6022,2062,LTV,1.5,NaT,False,True
15,6019,2074,NaN,1.5,NaT,True,False
16,6136,2082,NaN,NaN,NaT,True,False
17,6145,2044,LTV,NaN,2021-03-01,False,False
18,6024,2125,NaN,NaN,NaT,False,False
19,6195,2042,DSCR,NaN,2021-03-01,False,False
20,6064,2130,NaN,NaN,NaT,True,True
21,6064,2150,NaN,1.5,NaT,True,True
22,6060,2192,DSCR,1.5,NaT,False,True
23,6092,2024,LTV,NaN,NaT,False,True
24,6036,2152,NaN,1.5,2021-03-01,False,False
25,6085,2018,LTV,NaN,2021-03-01,False,False
26,6042,2068,NaN,1.5,2022-02-01,False,False
27,6011,2036,NaN,NaN,NaT,True,False
28,6074,2033,LTV,NaN,2021-03-01,False,True
29,6134,2035,DSCR,1.2,NaT,False,False
30,6152,2009,LTV,NaN,2021-03-01,False,False
31,6071,2164,DSCR,NaN,2022-02-01,False,False
32,6065,2013,LTV,1.2,2021-03-01,True,False
33,6157,2080,LTV,1.2,2022-02-01,False,False
34,6136,2140,LTV,1.5,2022-02-01,True,False
35,6166,2198,DSCR,1.2,2021-03-01,False,True
36,6181,2170,DSCR,1.5,NaT,False,False
37,6164,2028,NaN,1.5,NaT,True,True
38,6187,2197,DSCR,1.2,NaT,False,False
39,6083,2131,DSCR,NaN,2022-02-01,False,False
40,6079,2036,NaN,NaN,NaT,False,False
41,6064,2090,DSCR,NaN,NaT,True,False
42,6047,2183,LTV,NaN,NaT,False,True
43,6150,2079,DSCR,NaN,2022-02-01,False,False
44,6143,2037,DSCR,NaN,NaT,False,True
45,6160,2175,LTV,NaN,NaT,False,False
46,6034,2190,LTV,1.5,2021-03-01,True,False
47,6098,2195,DSCR,NaN,2022-02-01,False,False
48,6045,2191,DSCR,NaN,NaT,False,True
49,6178,2174,DSCR,1.5,2021-03-01,False,False
50,6054,2091,LTV,1.5,2022-02-01,True,True
51,6029,2039,NaN,1.5,NaT,False,True
52,6114,2123,DSCR,NaN,2021-03-01,False,False
53,6175,2044,DSCR,NaN,2022-02-01,False,False
54,6183,2095,LTV,1.5,2021-03-01,False,True
55,6020,2131,LTV,NaN,NaT,True,False
56,6065,2189,DSCR,NaN,2021-03-01,True,False
57,6031,2058,DSCR,NaN,NaT,False,True
58,6062,2051,LTV,1.5,2021-03-01,False,False
59,6107,2147,LTV,NaN,NaT,False,True
60,6056,2002,LTV,NaN,NaT,False,True
61,6014,2113,DSCR,NaN,NaT,False,False
62,6102,2149,NaN,NaN,NaT,False,True
63,6011,2110,LTV,NaN,2021-03-01,True,False
64,6046,2077,LTV,NaN,NaT,False,False
65,6001,2165,DSCR,NaN,NaT,True,True
66,6018,2074,NaN,NaN,NaT,False,False
67,6087,2142,NaN,NaN,NaT,False,False
68,6170,2093,DSCR,1.5,NaT,False,True
69,6155,2006,NaN,NaN,2022-02-01,False,False
70,6020,2106,NaN,1.2,2021-03-01,True,True
71,6007,2010,DSCR,NaN,2021-03-01,True,False
72,6068,2186,NaN,NaN,2022-02-01,False,True
73,6130,2120,DSCR,1.2,NaT,True,True
74,6149,2075,DSCR,NaN,NaT,False,True
75,6164,2097,DSCR,1.2,2022-02-01,True,False
76,6069,2124,LTV,NaN,2021-03-01,False,False
77,6034,2052,LTV,NaN,NaT,True,False
78,6006,2058,LTV,1.5,NaT,False,True
79,6030,2084,DSCR,NaN,NaT,False,True
80,6013,2052,DSCR,1.5,NaT,False,False
81,6172,2151,NaN,1.2,NaT,False,False
82,6054,2021,NaN,1.5,NaT,True,True
83,6164,2165,NaN,NaN,2022-02-01,True,True
84,6111,2070,DSCR,1.5,NaT,False,False
85,6108,2112,NaN,1.5,2022-02-01,False,False
86,6091,2032,NaN,NaN,2021-03-01,False,True
87,6164,2077,LTV,NaN,2022-02-01,True,False
88,6009,2151,DSCR,NaN,2021-03-01,False,False
89,6019,2054,NaN,1.5,2021-03-01,True,True

In [6]:
df["CovenantType"]=(df["CovenantType"]
                      .str.strip()
                      .str.upper())
df

,CovenantID,FacilityID,CovenantType,Threshold,LastCheckedDate,DuplicateExistsFlag,FacilityExistsFlag
0,6101,2085,DSCR,NaN,NaT,False,True
1,6110,2079,LTV,1.2,NaT,False,False
2,6049,2109,DSCR,1.2,2021-03-01,False,False
3,6100,2147,DSCR,NaN,NaT,False,True
4,6059,2117,LTV,1.2,2021-03-01,False,False
5,6137,2052,LTV,NaN,NaT,False,False
6,6159,2066,LTV,NaN,NaT,False,False
7,6130,2150,NaN,1.5,2021-03-01,True,True
8,6001,2041,NaN,1.2,NaT,True,False
9,6198,2101,DSCR,NaN,NaT,False,False
10,6005,2108,LTV,1.5,NaT,False,True
11,6199,2150,DSCR,1.5,2022-02-01,False,True
12,6007,2143,DSCR,1.5,2021-03-01,True,False
13,6103,2093,DSCR,1.2,NaT,False,True
14,6022,2062,LTV,1.5,NaT,False,True
15,6019,2074,NaN,1.5,NaT,True,False
16,6136,2082,NaN,NaN,NaT,True,False
17,6145,2044,LTV,NaN,2021-03-01,False,False
18,6024,2125,NaN,NaN,NaT,False,False
19,6195,2042,DSCR,NaN,2021-03-01,False,False
20,6064,2130,NaN,NaN,NaT,True,True
21,6064,2150,NaN,1.5,NaT,True,True
22,6060,2192,DSCR,1.5,NaT,False,True
23,6092,2024,LTV,NaN,NaT,False,True
24,6036,2152,NaN,1.5,2021-03-01,False,False
25,6085,2018,LTV,NaN,2021-03-01,False,False
26,6042,2068,NaN,1.5,2022-02-01,False,False
27,6011,2036,NaN,NaN,NaT,True,False
28,6074,2033,LTV,NaN,2021-03-01,False,True
29,6134,2035,DSCR,1.2,NaT,False,False
30,6152,2009,LTV,NaN,2021-03-01,False,False
31,6071,2164,DSCR,NaN,2022-02-01,False,False
32,6065,2013,LTV,1.2,2021-03-01,True,False
33,6157,2080,LTV,1.2,2022-02-01,False,False
34,6136,2140,LTV,1.5,2022-02-01,True,False
35,6166,2198,DSCR,1.2,2021-03-01,False,True
36,6181,2170,DSCR,1.5,NaT,False,False
37,6164,2028,NaN,1.5,NaT,True,True
38,6187,2197,DSCR,1.2,NaT,False,False
39,6083,2131,DSCR,NaN,2022-02-01,False,False
40,6079,2036,NaN,NaN,NaT,False,False
41,6064,2090,DSCR,NaN,NaT,True,False
42,6047,2183,LTV,NaN,NaT,False,True
43,6150,2079,DSCR,NaN,2022-02-01,False,False
44,6143,2037,DSCR,NaN,NaT,False,True
45,6160,2175,LTV,NaN,NaT,False,False
46,6034,2190,LTV,1.5,2021-03-01,True,False
47,6098,2195,DSCR,NaN,2022-02-01,False,False
48,6045,2191,DSCR,NaN,NaT,False,True
49,6178,2174,DSCR,1.5,2021-03-01,False,False
50,6054,2091,LTV,1.5,2022-02-01,True,True
51,6029,2039,NaN,1.5,NaT,False,True
52,6114,2123,DSCR,NaN,2021-03-01,False,False
53,6175,2044,DSCR,NaN,2022-02-01,False,False
54,6183,2095,LTV,1.5,2021-03-01,False,True
55,6020,2131,LTV,NaN,NaT,True,False
56,6065,2189,DSCR,NaN,2021-03-01,True,False
57,6031,2058,DSCR,NaN,NaT,False,True
58,6062,2051,LTV,1.5,2021-03-01,False,False
59,6107,2147,LTV,NaN,NaT,False,True
60,6056,2002,LTV,NaN,NaT,False,True
61,6014,2113,DSCR,NaN,NaT,False,False
62,6102,2149,NaN,NaN,NaT,False,True
63,6011,2110,LTV,NaN,2021-03-01,True,False
64,6046,2077,LTV,NaN,NaT,False,False
65,6001,2165,DSCR,NaN,NaT,True,True
66,6018,2074,NaN,NaN,NaT,False,False
67,6087,2142,NaN,NaN,NaT,False,False
68,6170,2093,DSCR,1.5,NaT,False,True
69,6155,2006,NaN,NaN,2022-02-01,False,False
70,6020,2106,NaN,1.2,2021-03-01,True,True
71,6007,2010,DSCR,NaN,2021-03-01,True,False
72,6068,2186,NaN,NaN,2022-02-01,False,True
73,6130,2120,DSCR,1.2,NaT,True,True
74,6149,2075,DSCR,NaN,NaT,False,True
75,6164,2097,DSCR,1.2,2022-02-01,True,False
76,6069,2124,LTV,NaN,2021-03-01,False,False
77,6034,2052,LTV,NaN,NaT,True,False
78,6006,2058,LTV,1.5,NaT,False,True
79,6030,2084,DSCR,NaN,NaT,False,True
80,6013,2052,DSCR,1.5,NaT,False,False
81,6172,2151,NaN,1.2,NaT,False,False
82,6054,2021,NaN,1.5,NaT,True,True
83,6164,2165,NaN,NaN,2022-02-01,True,True
84,6111,2070,DSCR,1.5,NaT,False,False
85,6108,2112,NaN,1.5,2022-02-01,False,False
86,6091,2032,NaN,NaN,2021-03-01,False,True
87,6164,2077,LTV,NaN,2022-02-01,True,False
88,6009,2151,DSCR,NaN,2021-03-01,False,False
89,6019,2054,NaN,1.5,2021-03-01,True,True

In [7]:
PROJECT_DIR = Path.cwd().parent

CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

output_file = CLEAN_DIR / "CovenantChecks_Clean.csv"

df.to_csv(output_file, index=False)

print("Saved successfully:", output_file)
print("Rows saved:", len(df))

Saved successfully: C:\Users\Madhura J\Desktop\Data Analyst Banking Project\data\Final_Version\Clean\CovenantChecks_Clean.csv
Rows saved: 90