In [29]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_DIR = Path.cwd().parent

file_path = (
    PROJECT_DIR
    / "data"
    / "Final_Version"
    / "Raw"
    / "Customers.csv"
)

print("File exists:", file_path.exists())

df = pd.read_csv(file_path)
pd.set_option('display.max.rows',None)
pd.set_option('display.max.columns',None)
df
df=df.sort_values('CustomerID')
df
print("Rows saved:", len(df))

File exists: True
Rows saved: 90

In [30]:
#To view the duplicates
duplicates = df[df.duplicated("CustomerID", keep=False)] \
            .sort_values("CustomerID")
duplicates
#To view the duplicates

    CustomerID CustomerName IncorporationDate Employees CreditScore
32        1014          NaN               NaN         5         850
0         1014  Global Corp               NaN        25         NaN
9         1015  ABC Pvt Ltd        15/02/2019         5         bad
86        1015          NaN          03-10-22         5         710
73        1020  Global Corp        15/02/2019        -3         620
17        1020          NaN        2018-01-15        -3         bad
82        1025          NaN        15/02/2019        25         620
40        1025  Global Corp        2018-01-15        -3         NaN
77        1035  ABC Pvt Ltd        2018-01-15       NaN         NaN
31        1035          NaN               NaN   unknown         710
52        1055      XYZ LLC        2018-01-15        -3         710
62        1055          NaN        2018-01-15        25         bad
21        1056          NaN               NaN        25         NaN
67        1056  Global Corp          03-10-22        25         bad
81        1066  ABC Pvt Ltd        15/02/2019         5         710
3         1066      XYZ LLC               NaN       NaN         NaN
46        1067          NaN               NaN   unknown         850
29        1067  ABC Pvt Ltd               NaN         5         620
19        1068          NaN               NaN       120         710
30        1068  Global Corp        15/02/2019       120         bad
69        1071          NaN        2018-01-15       NaN         bad
53        1071  Global Corp               NaN       NaN         620
56        1082  ABC Pvt Ltd        32/01/2020        25         NaN
28        1082      XYZ LLC        15/02/2019        25         NaN
39        1095          NaN               NaN         5         710
84        1095          NaN               NaN       NaN         920
59        1103  ABC Pvt Ltd        32/01/2020        -3         920
74        1103  Global Corp        32/01/2020       NaN         850
42        1106  ABC Pvt Ltd               NaN         5         710
85        1106  Global Corp        32/01/2020       NaN         920
58        1112          NaN        15/02/2019         5         710
61        1112      XYZ LLC        32/01/2020       120         bad
50        1114          NaN          03-10-22        25         710
41        1114  Global Corp          03-10-22   unknown         bad
49        1117  Global Corp        15/02/2019   unknown         620
1         1117          NaN        2018-01-15         5         NaN
24        1118  Global Corp          03-10-22        -3         620
15        1118          NaN        2018-01-15       NaN         620
37        1125          NaN        2018-01-15        -3         710
89        1125  Global Corp        32/01/2020   unknown         710
83        1125          NaN               NaN       120         850
5         1129      XYZ LLC          03-10-22       120         920
36        1129  ABC Pvt Ltd        2018-01-15        25         620
34        1134          NaN               NaN        -3         bad
47        1134  ABC Pvt Ltd        32/01/2020   unknown         620
45        1146      XYZ LLC        15/02/2019        -3         920
63        1146      XYZ LLC        32/01/2020   unknown         920

In [31]:

#last value value to be deleted
protected=[1095,
1103,
1134,
1125]
#first value to be deleted

to_drop=df.duplicated(subset=['CustomerID'],keep='first') & ~df['CustomerID'].isin(protected) #keep the first one for not in protected
#gives          the duplicated ids(second one)            &   not in protected list
#(second duplicate ids to be deleted and excludes the protected ids)(the ones to be deleted basically)

to_drop2=df.duplicated(subset=['CustomerID'],keep='last') & df['CustomerID'].isin(protected) #second one for protected
#gives          the duplicated ids(first one)            &  in protected list
#(first duplicate ids to be deleted and includes the protected ids)(the ones to be deleted basically)

all_to_drop=to_drop|to_drop2 #using or condition to combine all the ids to be deleted

df_clean=df[~all_to_drop] #creating a list which has non-deleted ids
df_dirty=df[all_to_drop]
"""just to review the IDs and check what must be deleted
to_view= df['CustomerID'].isin(protected) #view only the ids to be reviewed
df_view = df[to_view] 
df_view.sort_values('CustomerID')
"""

AUDIT_DIR = PROJECT_DIR / "data" / "Final_Version" / "Audit"
AUDIT_DIR.mkdir(parents=True, exist_ok=True)

audit_file = AUDIT_DIR / "Customers_Audit.csv"

df_dirty.to_csv(audit_file, index=False)


print("Saved successfully:", audit_file)
print("Rows saved:", len(df_dirty))
CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

clean_file = CLEAN_DIR / "Customers.csv"

df_clean.to_csv(clean_file, index=False)

df_clean.sort_values('CustomerID')
df=df_clean.sort_values('CustomerID')
df
print("Rows saved:", len(df))

#All the duplicate customer ids are deleted.

Saved successfully: C:\Users\Madhura J\Desktop\Data Analyst Banking Project\data\Final_Version\Audit\Customers_Audit.csv
Rows saved: 24
Rows saved: 66

In [32]:
df['IncorporationDate']=pd.to_datetime(df['IncorporationDate'],
format="mixed",
dayfirst=True,
errors="coerce")
df

    CustomerID CustomerName IncorporationDate Employees CreditScore
55        1007          NaN               NaT        25         bad
35        1010  Global Corp        2019-02-15         5         NaN
44        1011          NaN               NaT        25         850
68        1012  Global Corp               NaT        25         620
6         1013      XYZ LLC        2018-01-15       120         850
32        1014          NaN               NaT         5         850
9         1015  ABC Pvt Ltd        2019-02-15         5         bad
73        1020  Global Corp        2019-02-15        -3         620
57        1024      XYZ LLC        2022-10-03         5         620
82        1025          NaN        2019-02-15        25         620
22        1028  Global Corp        2022-10-03       NaN         NaN
71        1029          NaN        2022-10-03        25         bad
51        1030      XYZ LLC               NaT         5         710
8         1031          NaN        2019-02-15         5         620
77        1035  ABC Pvt Ltd        2018-01-15       NaN         NaN
38        1042  Global Corp        2022-10-03        25         710
87        1047  ABC Pvt Ltd        2022-10-03       NaN         NaN
65        1049          NaN        2018-01-15   unknown         710
76        1050      XYZ LLC               NaT       NaN         920
43        1054  Global Corp        2019-02-15        25         NaN
52        1055      XYZ LLC        2018-01-15        -3         710
21        1056          NaN               NaT        25         NaN
26        1061  ABC Pvt Ltd               NaT       NaN         620
64        1062  Global Corp               NaT       120         850
4         1065          NaN        2022-10-03       120         620
81        1066  ABC Pvt Ltd        2019-02-15         5         710
46        1067          NaN               NaT   unknown         850
19        1068          NaN               NaT       120         710
72        1070  Global Corp        2019-02-15        -3         bad
69        1071          NaN        2018-01-15       NaN         bad
75        1072          NaN        2018-01-15        25         620
54        1075          NaN        2022-10-03       NaN         620
20        1076      XYZ LLC        2022-10-03   unknown         620
16        1077          NaN        2022-10-03         5         bad
10        1079          NaN               NaT        25         850
56        1082  ABC Pvt Ltd               NaT        25         NaN
33        1084  Global Corp        2022-10-03       NaN         920
78        1085      XYZ LLC        2019-02-15        25         620
84        1095          NaN               NaT       NaN         920
25        1097  Global Corp        2019-02-15        -3         620
2         1099          NaN        2022-10-03         5         710
79        1101  ABC Pvt Ltd               NaT         5         850
48        1102      XYZ LLC               NaT       NaN         NaN
74        1103  Global Corp               NaT       NaN         850
7         1105          NaN        2022-10-03   unknown         710
42        1106  ABC Pvt Ltd               NaT         5         710
14        1108          NaN               NaT       120         NaN
12        1111          NaN               NaT   unknown         850
58        1112          NaN        2019-02-15         5         710
50        1114          NaN        2022-10-03        25         710
13        1115  ABC Pvt Ltd        2022-10-03       120         850
88        1116          NaN               NaT         5         920
49        1117  Global Corp        2019-02-15   unknown         620
24        1118  Global Corp        2022-10-03        -3         620
70        1120          NaN        2019-02-15        -3         620
27        1124  ABC Pvt Ltd               NaT       120         bad
83        1125          NaN               NaT       120         850
18        1126  Global Corp        2022-10-03        -3         850
5         1129      XYZ LLC        2022-10-03       120         920
47        1134  ABC Pvt Ltd               NaT   unknown         620
66        1136  ABC Pvt Ltd               NaT       NaN         NaN
60        1139          NaN        2018-01-15        -3         NaN
23        1140  Global Corp               NaT        25         710
80        1142  ABC Pvt Ltd               NaT        -3         NaN
45        1146      XYZ LLC        2019-02-15        -3         920
11        1147  ABC Pvt Ltd               NaT       120         920

In [33]:
df["Employees"]=pd.to_numeric(df["Employees"],errors="coerce")
df=df.replace(r'^\s*$',np.nan,regex=True)
df["Employees"] = df["Employees"].abs()
df

    CustomerID CustomerName IncorporationDate  Employees CreditScore
55        1007          NaN               NaT       25.0         bad
35        1010  Global Corp        2019-02-15        5.0         NaN
44        1011          NaN               NaT       25.0         850
68        1012  Global Corp               NaT       25.0         620
6         1013      XYZ LLC        2018-01-15      120.0         850
32        1014          NaN               NaT        5.0         850
9         1015  ABC Pvt Ltd        2019-02-15        5.0         bad
73        1020  Global Corp        2019-02-15        3.0         620
57        1024      XYZ LLC        2022-10-03        5.0         620
82        1025          NaN        2019-02-15       25.0         620
22        1028  Global Corp        2022-10-03        NaN         NaN
71        1029          NaN        2022-10-03       25.0         bad
51        1030      XYZ LLC               NaT        5.0         710
8         1031          NaN        2019-02-15        5.0         620
77        1035  ABC Pvt Ltd        2018-01-15        NaN         NaN
38        1042  Global Corp        2022-10-03       25.0         710
87        1047  ABC Pvt Ltd        2022-10-03        NaN         NaN
65        1049          NaN        2018-01-15        NaN         710
76        1050      XYZ LLC               NaT        NaN         920
43        1054  Global Corp        2019-02-15       25.0         NaN
52        1055      XYZ LLC        2018-01-15        3.0         710
21        1056          NaN               NaT       25.0         NaN
26        1061  ABC Pvt Ltd               NaT        NaN         620
64        1062  Global Corp               NaT      120.0         850
4         1065          NaN        2022-10-03      120.0         620
81        1066  ABC Pvt Ltd        2019-02-15        5.0         710
46        1067          NaN               NaT        NaN         850
19        1068          NaN               NaT      120.0         710
72        1070  Global Corp        2019-02-15        3.0         bad
69        1071          NaN        2018-01-15        NaN         bad
75        1072          NaN        2018-01-15       25.0         620
54        1075          NaN        2022-10-03        NaN         620
20        1076      XYZ LLC        2022-10-03        NaN         620
16        1077          NaN        2022-10-03        5.0         bad
10        1079          NaN               NaT       25.0         850
56        1082  ABC Pvt Ltd               NaT       25.0         NaN
33        1084  Global Corp        2022-10-03        NaN         920
78        1085      XYZ LLC        2019-02-15       25.0         620
84        1095          NaN               NaT        NaN         920
25        1097  Global Corp        2019-02-15        3.0         620
2         1099          NaN        2022-10-03        5.0         710
79        1101  ABC Pvt Ltd               NaT        5.0         850
48        1102      XYZ LLC               NaT        NaN         NaN
74        1103  Global Corp               NaT        NaN         850
7         1105          NaN        2022-10-03        NaN         710
42        1106  ABC Pvt Ltd               NaT        5.0         710
14        1108          NaN               NaT      120.0         NaN
12        1111          NaN               NaT        NaN         850
58        1112          NaN        2019-02-15        5.0         710
50        1114          NaN        2022-10-03       25.0         710
13        1115  ABC Pvt Ltd        2022-10-03      120.0         850
88        1116          NaN               NaT        5.0         920
49        1117  Global Corp        2019-02-15        NaN         620
24        1118  Global Corp        2022-10-03        3.0         620
70        1120          NaN        2019-02-15        3.0         620
27        1124  ABC Pvt Ltd               NaT      120.0         bad
83        1125          NaN               NaT      120.0         850
18        1126  Global Corp        2022-10-03        3.0         850
5         1129      XYZ LLC        2022-10-03      120.0         920
47        1134  ABC Pvt Ltd               NaT        NaN         620
66        1136  ABC Pvt Ltd               NaT        NaN         NaN
60        1139          NaN        2018-01-15        3.0         NaN
23        1140  Global Corp               NaT       25.0         710
80        1142  ABC Pvt Ltd               NaT        3.0         NaN
45        1146      XYZ LLC        2019-02-15        3.0         920
11        1147  ABC Pvt Ltd               NaT      120.0         920

In [34]:
df["CreditScore"]=pd.to_numeric(df["CreditScore"],errors="coerce")
df

    CustomerID CustomerName IncorporationDate  Employees  CreditScore
55        1007          NaN               NaT       25.0          NaN
35        1010  Global Corp        2019-02-15        5.0          NaN
44        1011          NaN               NaT       25.0        850.0
68        1012  Global Corp               NaT       25.0        620.0
6         1013      XYZ LLC        2018-01-15      120.0        850.0
32        1014          NaN               NaT        5.0        850.0
9         1015  ABC Pvt Ltd        2019-02-15        5.0          NaN
73        1020  Global Corp        2019-02-15        3.0        620.0
57        1024      XYZ LLC        2022-10-03        5.0        620.0
82        1025          NaN        2019-02-15       25.0        620.0
22        1028  Global Corp        2022-10-03        NaN          NaN
71        1029          NaN        2022-10-03       25.0          NaN
51        1030      XYZ LLC               NaT        5.0        710.0
8         1031          NaN        2019-02-15        5.0        620.0
77        1035  ABC Pvt Ltd        2018-01-15        NaN          NaN
38        1042  Global Corp        2022-10-03       25.0        710.0
87        1047  ABC Pvt Ltd        2022-10-03        NaN          NaN
65        1049          NaN        2018-01-15        NaN        710.0
76        1050      XYZ LLC               NaT        NaN        920.0
43        1054  Global Corp        2019-02-15       25.0          NaN
52        1055      XYZ LLC        2018-01-15        3.0        710.0
21        1056          NaN               NaT       25.0          NaN
26        1061  ABC Pvt Ltd               NaT        NaN        620.0
64        1062  Global Corp               NaT      120.0        850.0
4         1065          NaN        2022-10-03      120.0        620.0
81        1066  ABC Pvt Ltd        2019-02-15        5.0        710.0
46        1067          NaN               NaT        NaN        850.0
19        1068          NaN               NaT      120.0        710.0
72        1070  Global Corp        2019-02-15        3.0          NaN
69        1071          NaN        2018-01-15        NaN          NaN
75        1072          NaN        2018-01-15       25.0        620.0
54        1075          NaN        2022-10-03        NaN        620.0
20        1076      XYZ LLC        2022-10-03        NaN        620.0
16        1077          NaN        2022-10-03        5.0          NaN
10        1079          NaN               NaT       25.0        850.0
56        1082  ABC Pvt Ltd               NaT       25.0          NaN
33        1084  Global Corp        2022-10-03        NaN        920.0
78        1085      XYZ LLC        2019-02-15       25.0        620.0
84        1095          NaN               NaT        NaN        920.0
25        1097  Global Corp        2019-02-15        3.0        620.0
2         1099          NaN        2022-10-03        5.0        710.0
79        1101  ABC Pvt Ltd               NaT        5.0        850.0
48        1102      XYZ LLC               NaT        NaN          NaN
74        1103  Global Corp               NaT        NaN        850.0
7         1105          NaN        2022-10-03        NaN        710.0
42        1106  ABC Pvt Ltd               NaT        5.0        710.0
14        1108          NaN               NaT      120.0          NaN
12        1111          NaN               NaT        NaN        850.0
58        1112          NaN        2019-02-15        5.0        710.0
50        1114          NaN        2022-10-03       25.0        710.0
13        1115  ABC Pvt Ltd        2022-10-03      120.0        850.0
88        1116          NaN               NaT        5.0        920.0
49        1117  Global Corp        2019-02-15        NaN        620.0
24        1118  Global Corp        2022-10-03        3.0        620.0
70        1120          NaN        2019-02-15        3.0        620.0
27        1124  ABC Pvt Ltd               NaT      120.0          NaN
83        1125          NaN               NaT      120.0        850.0
18        1126  Global Corp        2022-10-03        3.0        850.0
5         1129      XYZ LLC        2022-10-03      120.0        920.0
47        1134  ABC Pvt Ltd               NaT        NaN        620.0
66        1136  ABC Pvt Ltd               NaT        NaN          NaN
60        1139          NaN        2018-01-15        3.0          NaN
23        1140  Global Corp               NaT       25.0        710.0
80        1142  ABC Pvt Ltd               NaT        3.0          NaN
45        1146      XYZ LLC        2019-02-15        3.0        920.0
11        1147  ABC Pvt Ltd               NaT      120.0        920.0

In [35]:
df["CustomerID"].is_unique

True

In [36]:
PROJECT_DIR = Path.cwd().parent

CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

output_file = CLEAN_DIR / "Customers_Clean.csv"

df.to_csv(output_file, index=False)

print("Saved successfully:", output_file)
print("Rows saved:", len(df))

Saved successfully: C:\Users\Madhura J\Desktop\Data Analyst Banking Project\data\Final_Version\Clean\Customers_Clean.csv
Rows saved: 66