In [14]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_DIR = Path.cwd().parent
print(Path.cwd().parent)
file_path = (
    PROJECT_DIR
    / "data"
    / "Final_Version"
    / "Raw"
    / "Facilities.csv"
)

print("File exists:", file_path.exists())

df = pd.read_csv(file_path)
pd.set_option('display.max.rows',None)
pd.set_option('display.max.columns',None)
df

df.sort_values("FacilityID")
df
print("Rows saved:", len(df))

C:\Users\Madhura J\Desktop\Data Analyst Banking Project
File exists: True
Rows saved: 90

In [15]:
df["FacilityID"].is_unique

False

In [16]:
duplicates = df[df.duplicated("FacilityID",keep=False)]\
.sort_values("FacilityID")

duplicates

protected=(2106,2119,2127,2173,2184,2186)

to_drop_second=df.duplicated(subset=['FacilityID'],keep="first") & ~df['FacilityID'].isin(protected)

to_drop_first=df.duplicated(subset=['FacilityID'],keep="last") & df['FacilityID'].isin(protected)

'''
df_first=df[to_drop_first]
df_first.sort_values('FacilityID')

df_second=df[to_drop_second]
df_second

#df_first.sort_values('FacilityID')
'''

all_to_drop=to_drop_second|to_drop_first

df_clean=df[~all_to_drop]
df_dirty=df[all_to_drop]

AUDIT_DIR=PROJECT_DIR/"data"/"Final_Version"/"Audit"
AUDIT_DIR.mkdir(parents=True, exist_ok=True)

audit_file = AUDIT_DIR / "Facilities_Audit.csv"

df_dirty.to_csv(audit_file, index=False)
print("Saved successfully:", audit_file)
print("Rows saved:", len(df_dirty))
df=df_clean.sort_values('FacilityID')
print("Rows saved:", len(df))



#2106,2119,2127,2173,2184,2186

Saved successfully: C:\Users\Madhura J\Desktop\Data Analyst Banking Project\data\Final_Version\Audit\Facilities_Audit.csv
Rows saved: 19
Rows saved: 71

In [17]:
df["FacilityID"].is_unique

True

In [18]:
df["FacilityType"]=(df["FacilityType"]
                    .str.strip()
                    .str.title()
)
df

,FacilityID,CustomerID,FacilityType,AmountApproved,StartDate,TenorMonths,Customer_Exists
14,2002,1147,NaN,500000.0,13/32/2020,18.5,NaN
27,2004,1038,Term Loan,-10000.0,01-01-2021,24,NaN
3,2005,1027,Overdraft,500000.0,01/15/2021,NaN,NaN
67,2014,1077,Term Loan,NaN,13/32/2020,24,NaN
65,2021,1080,Overdraft,NaN,13/32/2020,18.5,NaN
9,2022,1102,NaN,NaN,NaN,12,NaN
50,2023,1120,Term Loan,NaN,NaN,12,NaN
46,2024,1103,Term Loan,NaN,01-01-2021,NaN,NaN
11,2028,1059,NaN,-10000.0,13/32/2020,12,NaN
77,2029,1040,Term Loan,-10000.0,01-01-2021,18.5,NaN
6,2030,1064,Loan,NaN,01-01-2021,18.5,NaN
85,2031,1035,NaN,1500000.0,13/32/2020,abc,NaN
82,2032,1025,Term Loan,NaN,13/32/2020,18.5,NaN
81,2033,1072,Term Loan,-10000.0,13/32/2020,abc,NaN
16,2034,1110,Overdraft,NaN,13/32/2020,18.5,NaN
18,2037,1119,NaN,NaN,NaN,24,NaN
72,2039,1117,Loan,NaN,01/15/2021,18.5,NaN
35,2047,1056,Term Loan,-10000.0,01-01-2021,NaN,NaN
59,2048,1096,NaN,1500000.0,01-01-2021,18.5,NaN
32,2050,1043,Loan,500000.0,NaN,24,NaN
58,2054,1094,Overdraft,-10000.0,01/15/2021,NaN,NaN
54,2055,1048,Loan,1500000.0,NaN,abc,NaN
83,2057,1063,NaN,1500000.0,NaN,abc,NaN
30,2058,1142,Loan,1500000.0,01/15/2021,18.5,NaN
75,2062,1096,Term Loan,-10000.0,13/32/2020,24,NaN
74,2064,1103,Loan,-10000.0,NaN,12,NaN
36,2067,1138,Term Loan,NaN,01-01-2021,12,NaN
70,2072,1125,Term Loan,500000.0,01-01-2021,24,NaN
47,2075,1015,Loan,-10000.0,01-01-2021,12,NaN
45,2083,1138,Term Loan,1500000.0,NaN,12,NaN
13,2084,1048,Overdraft,1500000.0,13/32/2020,NaN,NaN
49,2085,1126,NaN,-10000.0,NaN,24,NaN
22,2086,1074,Loan,NaN,01/15/2021,18.5,NaN
55,2091,1120,NaN,1500000.0,13/32/2020,abc,NaN
34,2093,1002,Term Loan,NaN,01-01-2021,18.5,NaN
23,2094,1028,NaN,-10000.0,01-01-2021,12,NaN
68,2095,1145,Loan,NaN,13/32/2020,NaN,NaN
2,2100,1030,Overdraft,1500000.0,13/32/2020,24,NaN
56,2106,1087,Overdraft,-10000.0,NaN,18.5,NaN
88,2108,1076,Loan,-10000.0,01-01-2021,24,NaN
5,2111,1008,Term Loan,500000.0,NaN,abc,NaN
84,2115,1091,NaN,NaN,13/32/2020,18.5,NaN
69,2119,1128,Loan,500000.0,13/32/2020,12,NaN
80,2120,1065,Term Loan,500000.0,01-01-2021,18.5,NaN
39,2121,1016,Loan,NaN,13/32/2020,18.5,NaN
24,2127,1133,Term Loan,1500000.0,NaN,24,NaN
51,2130,1135,Loan,1500000.0,NaN,24,NaN
28,2133,1096,Loan,-10000.0,01-01-2021,18.5,NaN
10,2144,1120,Term Loan,NaN,01-01-2021,abc,NaN
20,2147,1080,Overdraft,1500000.0,01-01-2021,NaN,NaN
61,2149,1117,NaN,NaN,01-01-2021,18.5,NaN
12,2150,1124,NaN,1500000.0,01-01-2021,24,NaN
38,2153,1134,NaN,500000.0,NaN,18.5,NaN
25,2157,1036,Term Loan,-10000.0,NaN,NaN,NaN
33,2159,1008,Loan,1500000.0,01-01-2021,abc,NaN
21,2161,1007,Term Loan,1500000.0,01-01-2021,18.5,NaN
63,2163,1021,NaN,500000.0,01-01-2021,24,NaN
73,2165,1058,Loan,1500000.0,01-01-2021,18.5,NaN
31,2166,1063,Term Loan,500000.0,13/32/2020,abc,NaN
8,2168,1077,NaN,-10000.0,13/32/2020,24,NaN
26,2169,1034,NaN,NaN,NaN,18.5,NaN
53,2173,1146,NaN,NaN,NaN,18.5,NaN
66,2176,1049,Term Loan,500000.0,13/32/2020,abc,NaN
78,2183,1010,Overdraft,-10000.0,01-01-2021,24,NaN
79,2184,1021,Overdraft,-10000.0,01/15/2021,18.5,NaN
1,2185,1009,Overdraft,1500000.0,NaN,12,NaN
40,2186,1014,NaN,500000.0,NaN,abc,NaN
64,2191,1124,Loan,-10000.0,13/32/2020,NaN,NaN
0,2192,1106,Term Loan,500000.0,01-01-2021,12,NaN
15,2193,1076,Overdraft,NaN,01-01-2021,18.5,NaN
60,2198,1092,NaN,1500000.0,01/15/2021,12,NaN

In [19]:
df["AmountApproved"]=(df["AmountApproved"].abs())
df

,FacilityID,CustomerID,FacilityType,AmountApproved,StartDate,TenorMonths,Customer_Exists
14,2002,1147,NaN,500000.0,13/32/2020,18.5,NaN
27,2004,1038,Term Loan,10000.0,01-01-2021,24,NaN
3,2005,1027,Overdraft,500000.0,01/15/2021,NaN,NaN
67,2014,1077,Term Loan,NaN,13/32/2020,24,NaN
65,2021,1080,Overdraft,NaN,13/32/2020,18.5,NaN
9,2022,1102,NaN,NaN,NaN,12,NaN
50,2023,1120,Term Loan,NaN,NaN,12,NaN
46,2024,1103,Term Loan,NaN,01-01-2021,NaN,NaN
11,2028,1059,NaN,10000.0,13/32/2020,12,NaN
77,2029,1040,Term Loan,10000.0,01-01-2021,18.5,NaN
6,2030,1064,Loan,NaN,01-01-2021,18.5,NaN
85,2031,1035,NaN,1500000.0,13/32/2020,abc,NaN
82,2032,1025,Term Loan,NaN,13/32/2020,18.5,NaN
81,2033,1072,Term Loan,10000.0,13/32/2020,abc,NaN
16,2034,1110,Overdraft,NaN,13/32/2020,18.5,NaN
18,2037,1119,NaN,NaN,NaN,24,NaN
72,2039,1117,Loan,NaN,01/15/2021,18.5,NaN
35,2047,1056,Term Loan,10000.0,01-01-2021,NaN,NaN
59,2048,1096,NaN,1500000.0,01-01-2021,18.5,NaN
32,2050,1043,Loan,500000.0,NaN,24,NaN
58,2054,1094,Overdraft,10000.0,01/15/2021,NaN,NaN
54,2055,1048,Loan,1500000.0,NaN,abc,NaN
83,2057,1063,NaN,1500000.0,NaN,abc,NaN
30,2058,1142,Loan,1500000.0,01/15/2021,18.5,NaN
75,2062,1096,Term Loan,10000.0,13/32/2020,24,NaN
74,2064,1103,Loan,10000.0,NaN,12,NaN
36,2067,1138,Term Loan,NaN,01-01-2021,12,NaN
70,2072,1125,Term Loan,500000.0,01-01-2021,24,NaN
47,2075,1015,Loan,10000.0,01-01-2021,12,NaN
45,2083,1138,Term Loan,1500000.0,NaN,12,NaN
13,2084,1048,Overdraft,1500000.0,13/32/2020,NaN,NaN
49,2085,1126,NaN,10000.0,NaN,24,NaN
22,2086,1074,Loan,NaN,01/15/2021,18.5,NaN
55,2091,1120,NaN,1500000.0,13/32/2020,abc,NaN
34,2093,1002,Term Loan,NaN,01-01-2021,18.5,NaN
23,2094,1028,NaN,10000.0,01-01-2021,12,NaN
68,2095,1145,Loan,NaN,13/32/2020,NaN,NaN
2,2100,1030,Overdraft,1500000.0,13/32/2020,24,NaN
56,2106,1087,Overdraft,10000.0,NaN,18.5,NaN
88,2108,1076,Loan,10000.0,01-01-2021,24,NaN
5,2111,1008,Term Loan,500000.0,NaN,abc,NaN
84,2115,1091,NaN,NaN,13/32/2020,18.5,NaN
69,2119,1128,Loan,500000.0,13/32/2020,12,NaN
80,2120,1065,Term Loan,500000.0,01-01-2021,18.5,NaN
39,2121,1016,Loan,NaN,13/32/2020,18.5,NaN
24,2127,1133,Term Loan,1500000.0,NaN,24,NaN
51,2130,1135,Loan,1500000.0,NaN,24,NaN
28,2133,1096,Loan,10000.0,01-01-2021,18.5,NaN
10,2144,1120,Term Loan,NaN,01-01-2021,abc,NaN
20,2147,1080,Overdraft,1500000.0,01-01-2021,NaN,NaN
61,2149,1117,NaN,NaN,01-01-2021,18.5,NaN
12,2150,1124,NaN,1500000.0,01-01-2021,24,NaN
38,2153,1134,NaN,500000.0,NaN,18.5,NaN
25,2157,1036,Term Loan,10000.0,NaN,NaN,NaN
33,2159,1008,Loan,1500000.0,01-01-2021,abc,NaN
21,2161,1007,Term Loan,1500000.0,01-01-2021,18.5,NaN
63,2163,1021,NaN,500000.0,01-01-2021,24,NaN
73,2165,1058,Loan,1500000.0,01-01-2021,18.5,NaN
31,2166,1063,Term Loan,500000.0,13/32/2020,abc,NaN
8,2168,1077,NaN,10000.0,13/32/2020,24,NaN
26,2169,1034,NaN,NaN,NaN,18.5,NaN
53,2173,1146,NaN,NaN,NaN,18.5,NaN
66,2176,1049,Term Loan,500000.0,13/32/2020,abc,NaN
78,2183,1010,Overdraft,10000.0,01-01-2021,24,NaN
79,2184,1021,Overdraft,10000.0,01/15/2021,18.5,NaN
1,2185,1009,Overdraft,1500000.0,NaN,12,NaN
40,2186,1014,NaN,500000.0,NaN,abc,NaN
64,2191,1124,Loan,10000.0,13/32/2020,NaN,NaN
0,2192,1106,Term Loan,500000.0,01-01-2021,12,NaN
15,2193,1076,Overdraft,NaN,01-01-2021,18.5,NaN
60,2198,1092,NaN,1500000.0,01/15/2021,12,NaN

In [20]:
df["StartDate"]=pd.to_datetime(df["StartDate"],
                              format="mixed",
                               dayfirst=True,
                               errors="coerce")
df

,FacilityID,CustomerID,FacilityType,AmountApproved,StartDate,TenorMonths,Customer_Exists
14,2002,1147,NaN,500000.0,NaT,18.5,NaN
27,2004,1038,Term Loan,10000.0,2021-01-01,24,NaN
3,2005,1027,Overdraft,500000.0,2021-01-15,NaN,NaN
67,2014,1077,Term Loan,NaN,NaT,24,NaN
65,2021,1080,Overdraft,NaN,NaT,18.5,NaN
9,2022,1102,NaN,NaN,NaT,12,NaN
50,2023,1120,Term Loan,NaN,NaT,12,NaN
46,2024,1103,Term Loan,NaN,2021-01-01,NaN,NaN
11,2028,1059,NaN,10000.0,NaT,12,NaN
77,2029,1040,Term Loan,10000.0,2021-01-01,18.5,NaN
6,2030,1064,Loan,NaN,2021-01-01,18.5,NaN
85,2031,1035,NaN,1500000.0,NaT,abc,NaN
82,2032,1025,Term Loan,NaN,NaT,18.5,NaN
81,2033,1072,Term Loan,10000.0,NaT,abc,NaN
16,2034,1110,Overdraft,NaN,NaT,18.5,NaN
18,2037,1119,NaN,NaN,NaT,24,NaN
72,2039,1117,Loan,NaN,2021-01-15,18.5,NaN
35,2047,1056,Term Loan,10000.0,2021-01-01,NaN,NaN
59,2048,1096,NaN,1500000.0,2021-01-01,18.5,NaN
32,2050,1043,Loan,500000.0,NaT,24,NaN
58,2054,1094,Overdraft,10000.0,2021-01-15,NaN,NaN
54,2055,1048,Loan,1500000.0,NaT,abc,NaN
83,2057,1063,NaN,1500000.0,NaT,abc,NaN
30,2058,1142,Loan,1500000.0,2021-01-15,18.5,NaN
75,2062,1096,Term Loan,10000.0,NaT,24,NaN
74,2064,1103,Loan,10000.0,NaT,12,NaN
36,2067,1138,Term Loan,NaN,2021-01-01,12,NaN
70,2072,1125,Term Loan,500000.0,2021-01-01,24,NaN
47,2075,1015,Loan,10000.0,2021-01-01,12,NaN
45,2083,1138,Term Loan,1500000.0,NaT,12,NaN
13,2084,1048,Overdraft,1500000.0,NaT,NaN,NaN
49,2085,1126,NaN,10000.0,NaT,24,NaN
22,2086,1074,Loan,NaN,2021-01-15,18.5,NaN
55,2091,1120,NaN,1500000.0,NaT,abc,NaN
34,2093,1002,Term Loan,NaN,2021-01-01,18.5,NaN
23,2094,1028,NaN,10000.0,2021-01-01,12,NaN
68,2095,1145,Loan,NaN,NaT,NaN,NaN
2,2100,1030,Overdraft,1500000.0,NaT,24,NaN
56,2106,1087,Overdraft,10000.0,NaT,18.5,NaN
88,2108,1076,Loan,10000.0,2021-01-01,24,NaN
5,2111,1008,Term Loan,500000.0,NaT,abc,NaN
84,2115,1091,NaN,NaN,NaT,18.5,NaN
69,2119,1128,Loan,500000.0,NaT,12,NaN
80,2120,1065,Term Loan,500000.0,2021-01-01,18.5,NaN
39,2121,1016,Loan,NaN,NaT,18.5,NaN
24,2127,1133,Term Loan,1500000.0,NaT,24,NaN
51,2130,1135,Loan,1500000.0,NaT,24,NaN
28,2133,1096,Loan,10000.0,2021-01-01,18.5,NaN
10,2144,1120,Term Loan,NaN,2021-01-01,abc,NaN
20,2147,1080,Overdraft,1500000.0,2021-01-01,NaN,NaN
61,2149,1117,NaN,NaN,2021-01-01,18.5,NaN
12,2150,1124,NaN,1500000.0,2021-01-01,24,NaN
38,2153,1134,NaN,500000.0,NaT,18.5,NaN
25,2157,1036,Term Loan,10000.0,NaT,NaN,NaN
33,2159,1008,Loan,1500000.0,2021-01-01,abc,NaN
21,2161,1007,Term Loan,1500000.0,2021-01-01,18.5,NaN
63,2163,1021,NaN,500000.0,2021-01-01,24,NaN
73,2165,1058,Loan,1500000.0,2021-01-01,18.5,NaN
31,2166,1063,Term Loan,500000.0,NaT,abc,NaN
8,2168,1077,NaN,10000.0,NaT,24,NaN
26,2169,1034,NaN,NaN,NaT,18.5,NaN
53,2173,1146,NaN,NaN,NaT,18.5,NaN
66,2176,1049,Term Loan,500000.0,NaT,abc,NaN
78,2183,1010,Overdraft,10000.0,2021-01-01,24,NaN
79,2184,1021,Overdraft,10000.0,2021-01-15,18.5,NaN
1,2185,1009,Overdraft,1500000.0,NaT,12,NaN
40,2186,1014,NaN,500000.0,NaT,abc,NaN
64,2191,1124,Loan,10000.0,NaT,NaN,NaN
0,2192,1106,Term Loan,500000.0,2021-01-01,12,NaN
15,2193,1076,Overdraft,NaN,2021-01-01,18.5,NaN
60,2198,1092,NaN,1500000.0,2021-01-15,12,NaN

In [21]:
df["TenorMonths"]=pd.to_numeric(df["TenorMonths"],errors="coerce")
df

,FacilityID,CustomerID,FacilityType,AmountApproved,StartDate,TenorMonths,Customer_Exists
14,2002,1147,NaN,500000.0,NaT,18.5,NaN
27,2004,1038,Term Loan,10000.0,2021-01-01,24.0,NaN
3,2005,1027,Overdraft,500000.0,2021-01-15,NaN,NaN
67,2014,1077,Term Loan,NaN,NaT,24.0,NaN
65,2021,1080,Overdraft,NaN,NaT,18.5,NaN
9,2022,1102,NaN,NaN,NaT,12.0,NaN
50,2023,1120,Term Loan,NaN,NaT,12.0,NaN
46,2024,1103,Term Loan,NaN,2021-01-01,NaN,NaN
11,2028,1059,NaN,10000.0,NaT,12.0,NaN
77,2029,1040,Term Loan,10000.0,2021-01-01,18.5,NaN
6,2030,1064,Loan,NaN,2021-01-01,18.5,NaN
85,2031,1035,NaN,1500000.0,NaT,NaN,NaN
82,2032,1025,Term Loan,NaN,NaT,18.5,NaN
81,2033,1072,Term Loan,10000.0,NaT,NaN,NaN
16,2034,1110,Overdraft,NaN,NaT,18.5,NaN
18,2037,1119,NaN,NaN,NaT,24.0,NaN
72,2039,1117,Loan,NaN,2021-01-15,18.5,NaN
35,2047,1056,Term Loan,10000.0,2021-01-01,NaN,NaN
59,2048,1096,NaN,1500000.0,2021-01-01,18.5,NaN
32,2050,1043,Loan,500000.0,NaT,24.0,NaN
58,2054,1094,Overdraft,10000.0,2021-01-15,NaN,NaN
54,2055,1048,Loan,1500000.0,NaT,NaN,NaN
83,2057,1063,NaN,1500000.0,NaT,NaN,NaN
30,2058,1142,Loan,1500000.0,2021-01-15,18.5,NaN
75,2062,1096,Term Loan,10000.0,NaT,24.0,NaN
74,2064,1103,Loan,10000.0,NaT,12.0,NaN
36,2067,1138,Term Loan,NaN,2021-01-01,12.0,NaN
70,2072,1125,Term Loan,500000.0,2021-01-01,24.0,NaN
47,2075,1015,Loan,10000.0,2021-01-01,12.0,NaN
45,2083,1138,Term Loan,1500000.0,NaT,12.0,NaN
13,2084,1048,Overdraft,1500000.0,NaT,NaN,NaN
49,2085,1126,NaN,10000.0,NaT,24.0,NaN
22,2086,1074,Loan,NaN,2021-01-15,18.5,NaN
55,2091,1120,NaN,1500000.0,NaT,NaN,NaN
34,2093,1002,Term Loan,NaN,2021-01-01,18.5,NaN
23,2094,1028,NaN,10000.0,2021-01-01,12.0,NaN
68,2095,1145,Loan,NaN,NaT,NaN,NaN
2,2100,1030,Overdraft,1500000.0,NaT,24.0,NaN
56,2106,1087,Overdraft,10000.0,NaT,18.5,NaN
88,2108,1076,Loan,10000.0,2021-01-01,24.0,NaN
5,2111,1008,Term Loan,500000.0,NaT,NaN,NaN
84,2115,1091,NaN,NaN,NaT,18.5,NaN
69,2119,1128,Loan,500000.0,NaT,12.0,NaN
80,2120,1065,Term Loan,500000.0,2021-01-01,18.5,NaN
39,2121,1016,Loan,NaN,NaT,18.5,NaN
24,2127,1133,Term Loan,1500000.0,NaT,24.0,NaN
51,2130,1135,Loan,1500000.0,NaT,24.0,NaN
28,2133,1096,Loan,10000.0,2021-01-01,18.5,NaN
10,2144,1120,Term Loan,NaN,2021-01-01,NaN,NaN
20,2147,1080,Overdraft,1500000.0,2021-01-01,NaN,NaN
61,2149,1117,NaN,NaN,2021-01-01,18.5,NaN
12,2150,1124,NaN,1500000.0,2021-01-01,24.0,NaN
38,2153,1134,NaN,500000.0,NaT,18.5,NaN
25,2157,1036,Term Loan,10000.0,NaT,NaN,NaN
33,2159,1008,Loan,1500000.0,2021-01-01,NaN,NaN
21,2161,1007,Term Loan,1500000.0,2021-01-01,18.5,NaN
63,2163,1021,NaN,500000.0,2021-01-01,24.0,NaN
73,2165,1058,Loan,1500000.0,2021-01-01,18.5,NaN
31,2166,1063,Term Loan,500000.0,NaT,NaN,NaN
8,2168,1077,NaN,10000.0,NaT,24.0,NaN
26,2169,1034,NaN,NaN,NaT,18.5,NaN
53,2173,1146,NaN,NaN,NaT,18.5,NaN
66,2176,1049,Term Loan,500000.0,NaT,NaN,NaN
78,2183,1010,Overdraft,10000.0,2021-01-01,24.0,NaN
79,2184,1021,Overdraft,10000.0,2021-01-15,18.5,NaN
1,2185,1009,Overdraft,1500000.0,NaT,12.0,NaN
40,2186,1014,NaN,500000.0,NaT,NaN,NaN
64,2191,1124,Loan,10000.0,NaT,NaN,NaN
0,2192,1106,Term Loan,500000.0,2021-01-01,12.0,NaN
15,2193,1076,Overdraft,NaN,2021-01-01,18.5,NaN
60,2198,1092,NaN,1500000.0,2021-01-15,12.0,NaN

In [22]:
df=df.replace(r'^\s*$',np.nan,regex=True)
df

,FacilityID,CustomerID,FacilityType,AmountApproved,StartDate,TenorMonths,Customer_Exists
14,2002,1147,NaN,500000.0,NaT,18.5,NaN
27,2004,1038,Term Loan,10000.0,2021-01-01,24.0,NaN
3,2005,1027,Overdraft,500000.0,2021-01-15,NaN,NaN
67,2014,1077,Term Loan,NaN,NaT,24.0,NaN
65,2021,1080,Overdraft,NaN,NaT,18.5,NaN
9,2022,1102,NaN,NaN,NaT,12.0,NaN
50,2023,1120,Term Loan,NaN,NaT,12.0,NaN
46,2024,1103,Term Loan,NaN,2021-01-01,NaN,NaN
11,2028,1059,NaN,10000.0,NaT,12.0,NaN
77,2029,1040,Term Loan,10000.0,2021-01-01,18.5,NaN
6,2030,1064,Loan,NaN,2021-01-01,18.5,NaN
85,2031,1035,NaN,1500000.0,NaT,NaN,NaN
82,2032,1025,Term Loan,NaN,NaT,18.5,NaN
81,2033,1072,Term Loan,10000.0,NaT,NaN,NaN
16,2034,1110,Overdraft,NaN,NaT,18.5,NaN
18,2037,1119,NaN,NaN,NaT,24.0,NaN
72,2039,1117,Loan,NaN,2021-01-15,18.5,NaN
35,2047,1056,Term Loan,10000.0,2021-01-01,NaN,NaN
59,2048,1096,NaN,1500000.0,2021-01-01,18.5,NaN
32,2050,1043,Loan,500000.0,NaT,24.0,NaN
58,2054,1094,Overdraft,10000.0,2021-01-15,NaN,NaN
54,2055,1048,Loan,1500000.0,NaT,NaN,NaN
83,2057,1063,NaN,1500000.0,NaT,NaN,NaN
30,2058,1142,Loan,1500000.0,2021-01-15,18.5,NaN
75,2062,1096,Term Loan,10000.0,NaT,24.0,NaN
74,2064,1103,Loan,10000.0,NaT,12.0,NaN
36,2067,1138,Term Loan,NaN,2021-01-01,12.0,NaN
70,2072,1125,Term Loan,500000.0,2021-01-01,24.0,NaN
47,2075,1015,Loan,10000.0,2021-01-01,12.0,NaN
45,2083,1138,Term Loan,1500000.0,NaT,12.0,NaN
13,2084,1048,Overdraft,1500000.0,NaT,NaN,NaN
49,2085,1126,NaN,10000.0,NaT,24.0,NaN
22,2086,1074,Loan,NaN,2021-01-15,18.5,NaN
55,2091,1120,NaN,1500000.0,NaT,NaN,NaN
34,2093,1002,Term Loan,NaN,2021-01-01,18.5,NaN
23,2094,1028,NaN,10000.0,2021-01-01,12.0,NaN
68,2095,1145,Loan,NaN,NaT,NaN,NaN
2,2100,1030,Overdraft,1500000.0,NaT,24.0,NaN
56,2106,1087,Overdraft,10000.0,NaT,18.5,NaN
88,2108,1076,Loan,10000.0,2021-01-01,24.0,NaN
5,2111,1008,Term Loan,500000.0,NaT,NaN,NaN
84,2115,1091,NaN,NaN,NaT,18.5,NaN
69,2119,1128,Loan,500000.0,NaT,12.0,NaN
80,2120,1065,Term Loan,500000.0,2021-01-01,18.5,NaN
39,2121,1016,Loan,NaN,NaT,18.5,NaN
24,2127,1133,Term Loan,1500000.0,NaT,24.0,NaN
51,2130,1135,Loan,1500000.0,NaT,24.0,NaN
28,2133,1096,Loan,10000.0,2021-01-01,18.5,NaN
10,2144,1120,Term Loan,NaN,2021-01-01,NaN,NaN
20,2147,1080,Overdraft,1500000.0,2021-01-01,NaN,NaN
61,2149,1117,NaN,NaN,2021-01-01,18.5,NaN
12,2150,1124,NaN,1500000.0,2021-01-01,24.0,NaN
38,2153,1134,NaN,500000.0,NaT,18.5,NaN
25,2157,1036,Term Loan,10000.0,NaT,NaN,NaN
33,2159,1008,Loan,1500000.0,2021-01-01,NaN,NaN
21,2161,1007,Term Loan,1500000.0,2021-01-01,18.5,NaN
63,2163,1021,NaN,500000.0,2021-01-01,24.0,NaN
73,2165,1058,Loan,1500000.0,2021-01-01,18.5,NaN
31,2166,1063,Term Loan,500000.0,NaT,NaN,NaN
8,2168,1077,NaN,10000.0,NaT,24.0,NaN
26,2169,1034,NaN,NaN,NaT,18.5,NaN
53,2173,1146,NaN,NaN,NaT,18.5,NaN
66,2176,1049,Term Loan,500000.0,NaT,NaN,NaN
78,2183,1010,Overdraft,10000.0,2021-01-01,24.0,NaN
79,2184,1021,Overdraft,10000.0,2021-01-15,18.5,NaN
1,2185,1009,Overdraft,1500000.0,NaT,12.0,NaN
40,2186,1014,NaN,500000.0,NaT,NaN,NaN
64,2191,1124,Loan,10000.0,NaT,NaN,NaN
0,2192,1106,Term Loan,500000.0,2021-01-01,12.0,NaN
15,2193,1076,Overdraft,NaN,2021-01-01,18.5,NaN
60,2198,1092,NaN,1500000.0,2021-01-15,12.0,NaN

In [23]:
CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
customers_file = CLEAN_DIR / "Customers_Clean.csv"

df1=pd.read_csv(customers_file)

df[~df['CustomerID'].isin(df1['CustomerID'])].sort_values('CustomerID')

df['Customer_Exists']=df['CustomerID'].isin(df1['CustomerID'])

df

,FacilityID,CustomerID,FacilityType,AmountApproved,StartDate,TenorMonths,Customer_Exists
14,2002,1147,NaN,500000.0,NaT,18.5,True
27,2004,1038,Term Loan,10000.0,2021-01-01,24.0,False
3,2005,1027,Overdraft,500000.0,2021-01-15,NaN,False
67,2014,1077,Term Loan,NaN,NaT,24.0,True
65,2021,1080,Overdraft,NaN,NaT,18.5,False
9,2022,1102,NaN,NaN,NaT,12.0,True
50,2023,1120,Term Loan,NaN,NaT,12.0,True
46,2024,1103,Term Loan,NaN,2021-01-01,NaN,True
11,2028,1059,NaN,10000.0,NaT,12.0,False
77,2029,1040,Term Loan,10000.0,2021-01-01,18.5,False
6,2030,1064,Loan,NaN,2021-01-01,18.5,False
85,2031,1035,NaN,1500000.0,NaT,NaN,True
82,2032,1025,Term Loan,NaN,NaT,18.5,True
81,2033,1072,Term Loan,10000.0,NaT,NaN,True
16,2034,1110,Overdraft,NaN,NaT,18.5,False
18,2037,1119,NaN,NaN,NaT,24.0,False
72,2039,1117,Loan,NaN,2021-01-15,18.5,True
35,2047,1056,Term Loan,10000.0,2021-01-01,NaN,True
59,2048,1096,NaN,1500000.0,2021-01-01,18.5,False
32,2050,1043,Loan,500000.0,NaT,24.0,False
58,2054,1094,Overdraft,10000.0,2021-01-15,NaN,False
54,2055,1048,Loan,1500000.0,NaT,NaN,False
83,2057,1063,NaN,1500000.0,NaT,NaN,False
30,2058,1142,Loan,1500000.0,2021-01-15,18.5,True
75,2062,1096,Term Loan,10000.0,NaT,24.0,False
74,2064,1103,Loan,10000.0,NaT,12.0,True
36,2067,1138,Term Loan,NaN,2021-01-01,12.0,False
70,2072,1125,Term Loan,500000.0,2021-01-01,24.0,True
47,2075,1015,Loan,10000.0,2021-01-01,12.0,True
45,2083,1138,Term Loan,1500000.0,NaT,12.0,False
13,2084,1048,Overdraft,1500000.0,NaT,NaN,False
49,2085,1126,NaN,10000.0,NaT,24.0,True
22,2086,1074,Loan,NaN,2021-01-15,18.5,False
55,2091,1120,NaN,1500000.0,NaT,NaN,True
34,2093,1002,Term Loan,NaN,2021-01-01,18.5,False
23,2094,1028,NaN,10000.0,2021-01-01,12.0,True
68,2095,1145,Loan,NaN,NaT,NaN,False
2,2100,1030,Overdraft,1500000.0,NaT,24.0,True
56,2106,1087,Overdraft,10000.0,NaT,18.5,False
88,2108,1076,Loan,10000.0,2021-01-01,24.0,True
5,2111,1008,Term Loan,500000.0,NaT,NaN,False
84,2115,1091,NaN,NaN,NaT,18.5,False
69,2119,1128,Loan,500000.0,NaT,12.0,False
80,2120,1065,Term Loan,500000.0,2021-01-01,18.5,True
39,2121,1016,Loan,NaN,NaT,18.5,False
24,2127,1133,Term Loan,1500000.0,NaT,24.0,False
51,2130,1135,Loan,1500000.0,NaT,24.0,False
28,2133,1096,Loan,10000.0,2021-01-01,18.5,False
10,2144,1120,Term Loan,NaN,2021-01-01,NaN,True
20,2147,1080,Overdraft,1500000.0,2021-01-01,NaN,False
61,2149,1117,NaN,NaN,2021-01-01,18.5,True
12,2150,1124,NaN,1500000.0,2021-01-01,24.0,True
38,2153,1134,NaN,500000.0,NaT,18.5,True
25,2157,1036,Term Loan,10000.0,NaT,NaN,False
33,2159,1008,Loan,1500000.0,2021-01-01,NaN,False
21,2161,1007,Term Loan,1500000.0,2021-01-01,18.5,True
63,2163,1021,NaN,500000.0,2021-01-01,24.0,False
73,2165,1058,Loan,1500000.0,2021-01-01,18.5,False
31,2166,1063,Term Loan,500000.0,NaT,NaN,False
8,2168,1077,NaN,10000.0,NaT,24.0,True
26,2169,1034,NaN,NaN,NaT,18.5,False
53,2173,1146,NaN,NaN,NaT,18.5,True
66,2176,1049,Term Loan,500000.0,NaT,NaN,True
78,2183,1010,Overdraft,10000.0,2021-01-01,24.0,True
79,2184,1021,Overdraft,10000.0,2021-01-15,18.5,False
1,2185,1009,Overdraft,1500000.0,NaT,12.0,False
40,2186,1014,NaN,500000.0,NaT,NaN,True
64,2191,1124,Loan,10000.0,NaT,NaN,True
0,2192,1106,Term Loan,500000.0,2021-01-01,12.0,True
15,2193,1076,Overdraft,NaN,2021-01-01,18.5,True
60,2198,1092,NaN,1500000.0,2021-01-15,12.0,False

In [11]:
df["FacilityID"].is_unique

True

In [12]:
PROJECT_DIR = Path.cwd().parent

CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

output_file = CLEAN_DIR / "Facilities_Clean.csv"

df.to_csv(output_file, index=False)

print("Saved successfully:", output_file)
print("Rows saved:", len(df))

Saved successfully: C:\Users\Madhura J\Desktop\Data Analyst Banking Project\data\Final_Version\Clean\Facilities_Clean.csv
Rows saved: 71