In [7]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_DIR = Path.cwd().parent

file_path = (
    PROJECT_DIR
    / "data"
    / "Final_Version"
    / "Raw"
    / "Loans.csv"
)
print("File exists:", file_path.exists())

df = pd.read_csv(file_path)

print("Rows saved:", len(df))
print("File exists:", file_path.exists())

CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
output_file = CLEAN_DIR / "Facilities_Clean.csv"

print("File exists:", output_file.exists())
dff = pd.read_csv(output_file)
print("Rows saved:", len(dff))

pd.set_option("display.max.rows",None)
pd.set_option("display.max.columns",None)

df.sort_values("LoanID")

File exists: True
Rows saved: 90
File exists: True
File exists: True
Rows saved: 71

    LoanID  FacilityID  DisbursedAmount InterestRate LoanStatus
47    3003        2127              NaN          6.5     ACTIVE
79    3003        2068         600000.0          7.2        NaN
28    3009        2188         600000.0          6.5     ACTIVE
35    3012        2098         600000.0         rate     Active
30    3012        2126         600000.0          6.5        NaN
44    3014        2168         250000.0         rate     Active
31    3015        2047          -5000.0          NaN     Closed
36    3016        2199              NaN          7.2     ACTIVE
64    3016        2066              NaN          NaN     ACTIVE
29    3024        2009              NaN         rate     ACTIVE
59    3024        2108          -5000.0          7.2     Closed
14    3026        2066          -5000.0          NaN     ACTIVE
72    3029        2086         600000.0          7.2     ACTIVE
55    3031        2012         600000.0          7.2     Active
85    3033        2021         250000.0          NaN     Active
87    3034        2080              NaN         rate     ACTIVE
41    3035        2017         600000.0          7.2     ACTIVE
2     3040        2191          -5000.0          7.2     Closed
81    3042        2100          -5000.0          6.5     Active
56    3048        2145         250000.0         rate     Closed
22    3049        2183         250000.0          7.2     Closed
20    3054        2096          -5000.0         rate        NaN
37    3056        2117              NaN         rate     Closed
69    3062        2170         250000.0          7.2     Closed
43    3063        2049         600000.0          NaN     ACTIVE
23    3063        2030              NaN          NaN     Closed
78    3067        2077          -5000.0          NaN     Closed
39    3067        2099         600000.0          6.5        NaN
0     3069        2184              NaN          7.2     Active
7     3072        2198         250000.0          7.2     Active
61    3073        2068              NaN          7.2     ACTIVE
53    3075        2152              NaN          NaN     Closed
26    3077        2049              NaN          NaN        NaN
75    3078        2117         600000.0          NaN        NaN
52    3083        2159         600000.0          NaN     Closed
88    3084        2199              NaN         rate     Closed
68    3085        2138          -5000.0         rate        NaN
3     3086        2111         250000.0          NaN        NaN
48    3087        2111         600000.0          7.2     Active
66    3090        2106         250000.0         rate     ACTIVE
84    3093        2103              NaN          6.5     Closed
40    3098        2003              NaN          NaN     Closed
27    3099        2181         600000.0          6.5        NaN
62    3100        2186         600000.0         rate     Closed
17    3101        2151              NaN          NaN     Closed
60    3102        2176         600000.0          6.5     Active
9     3103        2029         250000.0          6.5     Closed
19    3104        2087         250000.0          NaN     ACTIVE
24    3104        2061              NaN          7.2        NaN
6     3105        2160          -5000.0          6.5     Closed
83    3105        2106         600000.0         rate     ACTIVE
4     3106        2040         250000.0          6.5     Active
1     3110        2197              NaN          NaN     Closed
12    3112        2168              NaN          NaN     Closed
38    3113        2144          -5000.0         rate        NaN
57    3120        2073         600000.0         rate        NaN
5     3125        2167          -5000.0          6.5     Closed
77    3128        2170          -5000.0          7.2        NaN
58    3134        2148         250000.0          7.2     Active
80    3135        2117         250000.0         rate     Closed
71    3137        2101         600000.0         rate        NaN
50    3141        2081              NaN         rate        NaN
73    3141        2182          -5000.0          NaN     ACTIVE
54    3142        2123          -5000.0          NaN     Active
86    3142        2005         250000.0          NaN     Closed
18    3146        2009              NaN          6.5        NaN
42    3146        2054          -5000.0         rate        NaN
11    3147        2090         600000.0          6.5     Active
45    3148        2168         250000.0         rate     ACTIVE
74    3150        2061         600000.0         rate     Closed
82    3151        2169         250000.0          6.5     Active
67    3154        2153         250000.0          6.5     Closed
70    3154        2074              NaN          7.2        NaN
21    3160        2094          -5000.0         rate     Closed
10    3161        2101              NaN          7.2     Active
34    3164        2039              NaN          NaN     Closed
49    3165        2130          -5000.0          NaN     Closed
25    3167        2037              NaN          6.5        NaN
89    3167        2183         600000.0         rate        NaN
33    3168        2059         600000.0          6.5        NaN
16    3170        2167         250000.0         rate     Closed
51    3171        2134              NaN          7.2     Active
32    3173        2039         600000.0          7.2     Closed
13    3177        2079          -5000.0         rate     Active
46    3180        2170              NaN          7.2     ACTIVE
15    3184        2016          -5000.0         rate     Active
76    3185        2024         600000.0         rate     ACTIVE
63    3191        2169              NaN          NaN        NaN
8     3192        2130          -5000.0          NaN     Active
65    3199        2097          -5000.0          6.5        NaN

In [8]:
df["LoanStatus"]=(df["LoanStatus"]
                      .str.strip()
                      .str.title())
df

    LoanID  FacilityID  DisbursedAmount InterestRate LoanStatus
0     3069        2184              NaN          7.2     Active
1     3110        2197              NaN          NaN     Closed
2     3040        2191          -5000.0          7.2     Closed
3     3086        2111         250000.0          NaN        NaN
4     3106        2040         250000.0          6.5     Active
5     3125        2167          -5000.0          6.5     Closed
6     3105        2160          -5000.0          6.5     Closed
7     3072        2198         250000.0          7.2     Active
8     3192        2130          -5000.0          NaN     Active
9     3103        2029         250000.0          6.5     Closed
10    3161        2101              NaN          7.2     Active
11    3147        2090         600000.0          6.5     Active
12    3112        2168              NaN          NaN     Closed
13    3177        2079          -5000.0         rate     Active
14    3026        2066          -5000.0          NaN     Active
15    3184        2016          -5000.0         rate     Active
16    3170        2167         250000.0         rate     Closed
17    3101        2151              NaN          NaN     Closed
18    3146        2009              NaN          6.5        NaN
19    3104        2087         250000.0          NaN     Active
20    3054        2096          -5000.0         rate        NaN
21    3160        2094          -5000.0         rate     Closed
22    3049        2183         250000.0          7.2     Closed
23    3063        2030              NaN          NaN     Closed
24    3104        2061              NaN          7.2        NaN
25    3167        2037              NaN          6.5        NaN
26    3077        2049              NaN          NaN        NaN
27    3099        2181         600000.0          6.5        NaN
28    3009        2188         600000.0          6.5     Active
29    3024        2009              NaN         rate     Active
30    3012        2126         600000.0          6.5        NaN
31    3015        2047          -5000.0          NaN     Closed
32    3173        2039         600000.0          7.2     Closed
33    3168        2059         600000.0          6.5        NaN
34    3164        2039              NaN          NaN     Closed
35    3012        2098         600000.0         rate     Active
36    3016        2199              NaN          7.2     Active
37    3056        2117              NaN         rate     Closed
38    3113        2144          -5000.0         rate        NaN
39    3067        2099         600000.0          6.5        NaN
40    3098        2003              NaN          NaN     Closed
41    3035        2017         600000.0          7.2     Active
42    3146        2054          -5000.0         rate        NaN
43    3063        2049         600000.0          NaN     Active
44    3014        2168         250000.0         rate     Active
45    3148        2168         250000.0         rate     Active
46    3180        2170              NaN          7.2     Active
47    3003        2127              NaN          6.5     Active
48    3087        2111         600000.0          7.2     Active
49    3165        2130          -5000.0          NaN     Closed
50    3141        2081              NaN         rate        NaN
51    3171        2134              NaN          7.2     Active
52    3083        2159         600000.0          NaN     Closed
53    3075        2152              NaN          NaN     Closed
54    3142        2123          -5000.0          NaN     Active
55    3031        2012         600000.0          7.2     Active
56    3048        2145         250000.0         rate     Closed
57    3120        2073         600000.0         rate        NaN
58    3134        2148         250000.0          7.2     Active
59    3024        2108          -5000.0          7.2     Closed
60    3102        2176         600000.0          6.5     Active
61    3073        2068              NaN          7.2     Active
62    3100        2186         600000.0         rate     Closed
63    3191        2169              NaN          NaN        NaN
64    3016        2066              NaN          NaN     Active
65    3199        2097          -5000.0          6.5        NaN
66    3090        2106         250000.0         rate     Active
67    3154        2153         250000.0          6.5     Closed
68    3085        2138          -5000.0         rate        NaN
69    3062        2170         250000.0          7.2     Closed
70    3154        2074              NaN          7.2        NaN
71    3137        2101         600000.0         rate        NaN
72    3029        2086         600000.0          7.2     Active
73    3141        2182          -5000.0          NaN     Active
74    3150        2061         600000.0         rate     Closed
75    3078        2117         600000.0          NaN        NaN
76    3185        2024         600000.0         rate     Active
77    3128        2170          -5000.0          7.2        NaN
78    3067        2077          -5000.0          NaN     Closed
79    3003        2068         600000.0          7.2        NaN
80    3135        2117         250000.0         rate     Closed
81    3042        2100          -5000.0          6.5     Active
82    3151        2169         250000.0          6.5     Active
83    3105        2106         600000.0         rate     Active
84    3093        2103              NaN          6.5     Closed
85    3033        2021         250000.0          NaN     Active
86    3142        2005         250000.0          NaN     Closed
87    3034        2080              NaN         rate     Active
88    3084        2199              NaN         rate     Closed
89    3167        2183         600000.0         rate        NaN

In [9]:
df[df["DisbursedAmount"] < 0].head()

    LoanID  FacilityID  DisbursedAmount InterestRate LoanStatus
2     3040        2191          -5000.0          7.2     Closed
5     3125        2167          -5000.0          6.5     Closed
6     3105        2160          -5000.0          6.5     Closed
8     3192        2130          -5000.0          NaN     Active
13    3177        2079          -5000.0         rate     Active

In [10]:
#select * from loans where loanstatus='Active' and DisbursedAmount<0
condition = ((df["LoanStatus"]=="Active") & (df["DisbursedAmount"]<0)) 

#select * from loans where disbursedamount<0 and loanstatus not in ('Active','Closed') and interestrate="rate"
condition2 = ((df["DisbursedAmount"]<0) & (~df["LoanStatus"].isin(["Active","Closed"])) & (df["InterestRate"].isin(["rate"])))

df1=df[condition] #display the df along with condition
df2=df[~condition] #display the df excluding condition
condition3 = (df["InterestRate"]=="rate")

condition4 = df["DisbursedAmount"]<0
df3=df[~(condition|condition2|condition3|condition4)]

df3=df[~(condition|condition2|condition3|condition4)]

df3

df_dirty=df[(condition|condition2|condition3|condition4)]

AUDIT_DIR=PROJECT_DIR/"data"/"Final_Version"/"Audit"
AUDIT_DIR.mkdir(parents=True, exist_ok=True)

audit_file = AUDIT_DIR / "Loans_Audit.csv"

df_dirty.to_csv(audit_file, index=False)
print("Saved successfully:", audit_file)
print("Rows saved:", len(df_dirty))

#no_of_bad_rows=(condition|condition2|condition3|condition4).sum()

#print("Rows to be removed:", no_of_bad_rows)
df=df3
df
print("Rows saved:", len(df))

Saved successfully: C:\Users\Madhura J\Desktop\Data Analyst Banking Project\data\Final_Version\Audit\Loans_Audit.csv
Rows saved: 40
Rows saved: 50

In [11]:
df["FacilityID"].isin(dff["FacilityID"]) 
df["LoanID"].is_unique

False

In [12]:
duplicates = df[df.duplicated("LoanID", keep=False)] \
            .sort_values("LoanID")
duplicates
df["DuplicatedLoanIDFlag"]=df.duplicated(subset="LoanID", keep=False)

C:\Users\Madhura J\AppData\Local\Temp\ipykernel_27960\914832715.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["DuplicatedLoanIDFlag"]=df.duplicated(subset="LoanID", keep=False)

In [13]:
df=df.copy()
df["DuplicatedLoanIDFlag"] = df.duplicated(subset="LoanID", keep=False)
df

,LoanID,FacilityID,DisbursedAmount,InterestRate,LoanStatus,DuplicatedLoanIDFlag
0,3069,2184,NaN,7.2,Active,False
1,3110,2197,NaN,NaN,Closed,False
3,3086,2111,250000.0,NaN,NaN,False
4,3106,2040,250000.0,6.5,Active,False
7,3072,2198,250000.0,7.2,Active,False
9,3103,2029,250000.0,6.5,Closed,False
10,3161,2101,NaN,7.2,Active,False
11,3147,2090,600000.0,6.5,Active,False
12,3112,2168,NaN,NaN,Closed,False
17,3101,2151,NaN,NaN,Closed,False
18,3146,2009,NaN,6.5,NaN,False
19,3104,2087,250000.0,NaN,Active,True
22,3049,2183,250000.0,7.2,Closed,False
23,3063,2030,NaN,NaN,Closed,True
24,3104,2061,NaN,7.2,NaN,True
25,3167,2037,NaN,6.5,NaN,False
26,3077,2049,NaN,NaN,NaN,False
27,3099,2181,600000.0,6.5,NaN,False
28,3009,2188,600000.0,6.5,Active,False
30,3012,2126,600000.0,6.5,NaN,False
32,3173,2039,600000.0,7.2,Closed,False
33,3168,2059,600000.0,6.5,NaN,False
34,3164,2039,NaN,NaN,Closed,False
36,3016,2199,NaN,7.2,Active,True
39,3067,2099,600000.0,6.5,NaN,False
40,3098,2003,NaN,NaN,Closed,False
41,3035,2017,600000.0,7.2,Active,False
43,3063,2049,600000.0,NaN,Active,True
46,3180,2170,NaN,7.2,Active,False
47,3003,2127,NaN,6.5,Active,True
48,3087,2111,600000.0,7.2,Active,False
51,3171,2134,NaN,7.2,Active,False
52,3083,2159,600000.0,NaN,Closed,False
53,3075,2152,NaN,NaN,Closed,False
55,3031,2012,600000.0,7.2,Active,False
58,3134,2148,250000.0,7.2,Active,False
60,3102,2176,600000.0,6.5,Active,False
61,3073,2068,NaN,7.2,Active,False
63,3191,2169,NaN,NaN,NaN,False
64,3016,2066,NaN,NaN,Active,True
67,3154,2153,250000.0,6.5,Closed,True
69,3062,2170,250000.0,7.2,Closed,False
70,3154,2074,NaN,7.2,NaN,True
72,3029,2086,600000.0,7.2,Active,False
75,3078,2117,600000.0,NaN,NaN,False
79,3003,2068,600000.0,7.2,NaN,True
82,3151,2169,250000.0,6.5,Active,False
84,3093,2103,NaN,6.5,Closed,False
85,3033,2021,250000.0,NaN,Active,False
86,3142,2005,250000.0,NaN,Closed,False

In [14]:
df["FacilitiesExistsFlag"] = df["FacilityID"].isin(dff["FacilityID"])
df

,LoanID,FacilityID,DisbursedAmount,InterestRate,LoanStatus,DuplicatedLoanIDFlag,FacilitiesExistsFlag
0,3069,2184,NaN,7.2,Active,False,True
1,3110,2197,NaN,NaN,Closed,False,False
3,3086,2111,250000.0,NaN,NaN,False,True
4,3106,2040,250000.0,6.5,Active,False,False
7,3072,2198,250000.0,7.2,Active,False,True
9,3103,2029,250000.0,6.5,Closed,False,True
10,3161,2101,NaN,7.2,Active,False,False
11,3147,2090,600000.0,6.5,Active,False,False
12,3112,2168,NaN,NaN,Closed,False,True
17,3101,2151,NaN,NaN,Closed,False,False
18,3146,2009,NaN,6.5,NaN,False,False
19,3104,2087,250000.0,NaN,Active,True,False
22,3049,2183,250000.0,7.2,Closed,False,True
23,3063,2030,NaN,NaN,Closed,True,True
24,3104,2061,NaN,7.2,NaN,True,False
25,3167,2037,NaN,6.5,NaN,False,True
26,3077,2049,NaN,NaN,NaN,False,False
27,3099,2181,600000.0,6.5,NaN,False,False
28,3009,2188,600000.0,6.5,Active,False,False
30,3012,2126,600000.0,6.5,NaN,False,False
32,3173,2039,600000.0,7.2,Closed,False,True
33,3168,2059,600000.0,6.5,NaN,False,False
34,3164,2039,NaN,NaN,Closed,False,True
36,3016,2199,NaN,7.2,Active,True,False
39,3067,2099,600000.0,6.5,NaN,False,False
40,3098,2003,NaN,NaN,Closed,False,False
41,3035,2017,600000.0,7.2,Active,False,False
43,3063,2049,600000.0,NaN,Active,True,False
46,3180,2170,NaN,7.2,Active,False,False
47,3003,2127,NaN,6.5,Active,True,True
48,3087,2111,600000.0,7.2,Active,False,True
51,3171,2134,NaN,7.2,Active,False,False
52,3083,2159,600000.0,NaN,Closed,False,True
53,3075,2152,NaN,NaN,Closed,False,False
55,3031,2012,600000.0,7.2,Active,False,False
58,3134,2148,250000.0,7.2,Active,False,False
60,3102,2176,600000.0,6.5,Active,False,True
61,3073,2068,NaN,7.2,Active,False,False
63,3191,2169,NaN,NaN,NaN,False,True
64,3016,2066,NaN,NaN,Active,True,False
67,3154,2153,250000.0,6.5,Closed,True,True
69,3062,2170,250000.0,7.2,Closed,False,False
70,3154,2074,NaN,7.2,NaN,True,False
72,3029,2086,600000.0,7.2,Active,False,True
75,3078,2117,600000.0,NaN,NaN,False,False
79,3003,2068,600000.0,7.2,NaN,True,False
82,3151,2169,250000.0,6.5,Active,False,True
84,3093,2103,NaN,6.5,Closed,False,False
85,3033,2021,250000.0,NaN,Active,False,True
86,3142,2005,250000.0,NaN,Closed,False,True

In [15]:
PROJECT_DIR = Path.cwd().parent

CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

output_file = CLEAN_DIR / "Loans_Clean.csv"

df.to_csv(output_file, index=False)

print("Saved successfully:", output_file)
print("Rows saved:", len(df))

Saved successfully: C:\Users\Madhura J\Desktop\Data Analyst Banking Project\data\Final_Version\Clean\Loans_Clean.csv
Rows saved: 50