In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

PROJECT_DIR = Path.cwd().parent

file_path = (
    PROJECT_DIR
    / "data"
    / "Final_Version"
    / "Raw"
    / "Payments.csv"
)
print("File exists:", file_path.exists())
df = pd.read_csv(file_path)
print("Rows saved:", len(df))

CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
output_file = CLEAN_DIR / "Facilities_Clean.csv"

print("File exists:", output_file.exists())

df2 = pd.read_csv(output_file)
print("Rows saved:", len(df2))

pd.set_option("display.max.rows",None)
pd.set_option("display.max.columns",None)

df.sort_values("PaymentID")

File exists: True
Rows saved: 90
File exists: True
Rows saved: 71

    PaymentID  FacilityID PaymentDate   Amount   Status
0        7001        2176         NaN   5000.0  partial
1        7002        2159  2022-07-15   5000.0   OnTime
2        7003        2045         NaN      NaN   Missed
3        7004        2167         NaN   5000.0      NaN
4        7005        2014  2022-07-15   -200.0   OnTime
5        7006        2057         NaN   5000.0   Missed
6        7007        2141         NaN  15000.0   Missed
7        7008        2061         NaN   5000.0      NaN
8        7009        2146         NaN   5000.0   ONTIME
9        7010        2174  15/08/2023   5000.0   Missed
10       7011        2014         NaN   5000.0  partial
11       7012        2005  15/08/2023      NaN   OnTime
12       7013        2188         NaN   -200.0      NaN
13       7014        2104  2022-07-15  15000.0      NaN
14       7015        2101  2022-07-15   -200.0  partial
15       7016        2093         NaN      NaN  partial
16       7017        2087  15/08/2023      NaN  partial
17       7018        2138  15/08/2023      NaN  partial
18       7019        2116         NaN  15000.0      NaN
19       7020        2033  2022-07-15   5000.0   Missed
20       7021        2125         NaN      NaN   Missed
21       7022        2133  15/08/2023  15000.0  partial
22       7023        2023  2022-07-15  15000.0   OnTime
23       7024        2075         NaN      NaN      NaN
24       7025        2158  2022-07-15      NaN  partial
25       7026        2124  2022-07-15  15000.0  partial
26       7027        2028         NaN      NaN   ONTIME
27       7028        2008         NaN  15000.0   ONTIME
28       7029        2116  2022-07-15   5000.0   Missed
29       7030        2092         NaN   -200.0  partial
30       7031        2192         NaN   5000.0  partial
31       7032        2104         NaN   5000.0  partial
32       7033        2186  2022-07-15   -200.0      NaN
33       7034        2043         NaN   5000.0      NaN
34       7035        2090         NaN   -200.0  partial
35       7036        2028         NaN   -200.0   ONTIME
36       7037        2115  15/08/2023      NaN   Missed
37       7038        2038         NaN  15000.0   Missed
38       7039        2098         NaN  15000.0  partial
39       7040        2069  2022-07-15   -200.0      NaN
40       7041        2037         NaN   -200.0   ONTIME
41       7042        2020         NaN  15000.0   Missed
42       7043        2102  15/08/2023   5000.0   OnTime
43       7044        2189         NaN      NaN  partial
44       7045        2040  15/08/2023   -200.0   Missed
45       7046        2081         NaN   5000.0   Missed
46       7047        2045         NaN      NaN   Missed
47       7048        2161         NaN   -200.0   ONTIME
48       7049        2083  2022-07-15   5000.0   Missed
49       7050        2194         NaN      NaN  partial
50       7051        2049  15/08/2023   5000.0   ONTIME
51       7052        2017         NaN      NaN   OnTime
52       7053        2116         NaN   5000.0   ONTIME
53       7054        2130  15/08/2023   -200.0   OnTime
54       7055        2198  15/08/2023  15000.0   ONTIME
55       7056        2174  15/08/2023   5000.0  partial
56       7057        2176         NaN  15000.0   OnTime
57       7058        2127  15/08/2023      NaN  partial
58       7059        2072  15/08/2023  15000.0   ONTIME
59       7060        2086  15/08/2023   5000.0      NaN
60       7061        2027  2022-07-15      NaN  partial
61       7062        2086  15/08/2023  15000.0   ONTIME
62       7063        2073  2022-07-15  15000.0   Missed
63       7064        2008  2022-07-15   5000.0   OnTime
64       7065        2041         NaN  15000.0   OnTime
65       7066        2107  2022-07-15   5000.0      NaN
66       7067        2074         NaN      NaN      NaN
67       7068        2198         NaN   -200.0   OnTime
68       7069        2096         NaN      NaN   ONTIME
69       7070        2191  15/08/2023      NaN   OnTime
70       7071        2132  2022-07-15   5000.0   ONTIME
71       7072        2009         NaN      NaN   ONTIME
72       7073        2041         NaN  15000.0   ONTIME
73       7074        2141         NaN   -200.0   Missed
74       7075        2109  2022-07-15   -200.0   OnTime
75       7076        2061  2022-07-15  15000.0      NaN
76       7077        2104  15/08/2023   5000.0  partial
77       7078        2180  2022-07-15   -200.0  partial
78       7079        2078         NaN      NaN   OnTime
79       7080        2009  2022-07-15   -200.0  partial
80       7081        2062  15/08/2023  15000.0      NaN
81       7082        2187         NaN   -200.0   OnTime
82       7083        2152         NaN  15000.0  partial
83       7084        2167  2022-07-15   5000.0   ONTIME
84       7085        2182  15/08/2023      NaN  partial
85       7086        2024         NaN      NaN   Missed
86       7087        2057         NaN   5000.0      NaN
87       7088        2012         NaN   5000.0   OnTime
88       7089        2001         NaN      NaN   ONTIME
89       7090        2167         NaN      NaN   ONTIME

In [2]:
df["PaymentID"].is_unique
df["FacilityID"].isin(df2["FacilityID"])

0      True
1      True
2     False
3     False
4      True
5      True
6     False
7     False
8     False
9     False
10     True
11     True
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19     True
20    False
21     True
22     True
23     True
24    False
25    False
26     True
27    False
28    False
29    False
30     True
31    False
32     True
33    False
34    False
35     True
36     True
37    False
38    False
39    False
40     True
41    False
42    False
43    False
44    False
45    False
46    False
47     True
48     True
49    False
50    False
51    False
52    False
53     True
54     True
55    False
56     True
57     True
58     True
59     True
60    False
61     True
62    False
63    False
64    False
65    False
66    False
67     True
68    False
69     True
70    False
71    False
72    False
73    False
74    False
75    False
76    False
77    False
78    False
79    False
80     True
81    False
82    False
83    False
84    False
85     True
86     True
87    False
88    False
89    False
Name: FacilityID, dtype: bool

In [3]:
df["Status"]=(df["Status"]
                      .str.strip()
                      .str.title())
df

    PaymentID  FacilityID PaymentDate   Amount   Status
0        7001        2176         NaN   5000.0  Partial
1        7002        2159  2022-07-15   5000.0   Ontime
2        7003        2045         NaN      NaN   Missed
3        7004        2167         NaN   5000.0      NaN
4        7005        2014  2022-07-15   -200.0   Ontime
5        7006        2057         NaN   5000.0   Missed
6        7007        2141         NaN  15000.0   Missed
7        7008        2061         NaN   5000.0      NaN
8        7009        2146         NaN   5000.0   Ontime
9        7010        2174  15/08/2023   5000.0   Missed
10       7011        2014         NaN   5000.0  Partial
11       7012        2005  15/08/2023      NaN   Ontime
12       7013        2188         NaN   -200.0      NaN
13       7014        2104  2022-07-15  15000.0      NaN
14       7015        2101  2022-07-15   -200.0  Partial
15       7016        2093         NaN      NaN  Partial
16       7017        2087  15/08/2023      NaN  Partial
17       7018        2138  15/08/2023      NaN  Partial
18       7019        2116         NaN  15000.0      NaN
19       7020        2033  2022-07-15   5000.0   Missed
20       7021        2125         NaN      NaN   Missed
21       7022        2133  15/08/2023  15000.0  Partial
22       7023        2023  2022-07-15  15000.0   Ontime
23       7024        2075         NaN      NaN      NaN
24       7025        2158  2022-07-15      NaN  Partial
25       7026        2124  2022-07-15  15000.0  Partial
26       7027        2028         NaN      NaN   Ontime
27       7028        2008         NaN  15000.0   Ontime
28       7029        2116  2022-07-15   5000.0   Missed
29       7030        2092         NaN   -200.0  Partial
30       7031        2192         NaN   5000.0  Partial
31       7032        2104         NaN   5000.0  Partial
32       7033        2186  2022-07-15   -200.0      NaN
33       7034        2043         NaN   5000.0      NaN
34       7035        2090         NaN   -200.0  Partial
35       7036        2028         NaN   -200.0   Ontime
36       7037        2115  15/08/2023      NaN   Missed
37       7038        2038         NaN  15000.0   Missed
38       7039        2098         NaN  15000.0  Partial
39       7040        2069  2022-07-15   -200.0      NaN
40       7041        2037         NaN   -200.0   Ontime
41       7042        2020         NaN  15000.0   Missed
42       7043        2102  15/08/2023   5000.0   Ontime
43       7044        2189         NaN      NaN  Partial
44       7045        2040  15/08/2023   -200.0   Missed
45       7046        2081         NaN   5000.0   Missed
46       7047        2045         NaN      NaN   Missed
47       7048        2161         NaN   -200.0   Ontime
48       7049        2083  2022-07-15   5000.0   Missed
49       7050        2194         NaN      NaN  Partial
50       7051        2049  15/08/2023   5000.0   Ontime
51       7052        2017         NaN      NaN   Ontime
52       7053        2116         NaN   5000.0   Ontime
53       7054        2130  15/08/2023   -200.0   Ontime
54       7055        2198  15/08/2023  15000.0   Ontime
55       7056        2174  15/08/2023   5000.0  Partial
56       7057        2176         NaN  15000.0   Ontime
57       7058        2127  15/08/2023      NaN  Partial
58       7059        2072  15/08/2023  15000.0   Ontime
59       7060        2086  15/08/2023   5000.0      NaN
60       7061        2027  2022-07-15      NaN  Partial
61       7062        2086  15/08/2023  15000.0   Ontime
62       7063        2073  2022-07-15  15000.0   Missed
63       7064        2008  2022-07-15   5000.0   Ontime
64       7065        2041         NaN  15000.0   Ontime
65       7066        2107  2022-07-15   5000.0      NaN
66       7067        2074         NaN      NaN      NaN
67       7068        2198         NaN   -200.0   Ontime
68       7069        2096         NaN      NaN   Ontime
69       7070        2191  15/08/2023      NaN   Ontime
70       7071        2132  2022-07-15   5000.0   Ontime
71       7072        2009         NaN      NaN   Ontime
72       7073        2041         NaN  15000.0   Ontime
73       7074        2141         NaN   -200.0   Missed
74       7075        2109  2022-07-15   -200.0   Ontime
75       7076        2061  2022-07-15  15000.0      NaN
76       7077        2104  15/08/2023   5000.0  Partial
77       7078        2180  2022-07-15   -200.0  Partial
78       7079        2078         NaN      NaN   Ontime
79       7080        2009  2022-07-15   -200.0  Partial
80       7081        2062  15/08/2023  15000.0      NaN
81       7082        2187         NaN   -200.0   Ontime
82       7083        2152         NaN  15000.0  Partial
83       7084        2167  2022-07-15   5000.0   Ontime
84       7085        2182  15/08/2023      NaN  Partial
85       7086        2024         NaN      NaN   Missed
86       7087        2057         NaN   5000.0      NaN
87       7088        2012         NaN   5000.0   Ontime
88       7089        2001         NaN      NaN   Ontime
89       7090        2167         NaN      NaN   Ontime

In [4]:
df["PaymentID"].is_unique

True

In [5]:
df['PaymentDate']=pd.to_datetime(df['PaymentDate'],
format="mixed",
dayfirst=True,
errors="coerce")
df

    PaymentID  FacilityID PaymentDate   Amount   Status
0        7001        2176         NaT   5000.0  Partial
1        7002        2159  2022-07-15   5000.0   Ontime
2        7003        2045         NaT      NaN   Missed
3        7004        2167         NaT   5000.0      NaN
4        7005        2014  2022-07-15   -200.0   Ontime
5        7006        2057         NaT   5000.0   Missed
6        7007        2141         NaT  15000.0   Missed
7        7008        2061         NaT   5000.0      NaN
8        7009        2146         NaT   5000.0   Ontime
9        7010        2174  2023-08-15   5000.0   Missed
10       7011        2014         NaT   5000.0  Partial
11       7012        2005  2023-08-15      NaN   Ontime
12       7013        2188         NaT   -200.0      NaN
13       7014        2104  2022-07-15  15000.0      NaN
14       7015        2101  2022-07-15   -200.0  Partial
15       7016        2093         NaT      NaN  Partial
16       7017        2087  2023-08-15      NaN  Partial
17       7018        2138  2023-08-15      NaN  Partial
18       7019        2116         NaT  15000.0      NaN
19       7020        2033  2022-07-15   5000.0   Missed
20       7021        2125         NaT      NaN   Missed
21       7022        2133  2023-08-15  15000.0  Partial
22       7023        2023  2022-07-15  15000.0   Ontime
23       7024        2075         NaT      NaN      NaN
24       7025        2158  2022-07-15      NaN  Partial
25       7026        2124  2022-07-15  15000.0  Partial
26       7027        2028         NaT      NaN   Ontime
27       7028        2008         NaT  15000.0   Ontime
28       7029        2116  2022-07-15   5000.0   Missed
29       7030        2092         NaT   -200.0  Partial
30       7031        2192         NaT   5000.0  Partial
31       7032        2104         NaT   5000.0  Partial
32       7033        2186  2022-07-15   -200.0      NaN
33       7034        2043         NaT   5000.0      NaN
34       7035        2090         NaT   -200.0  Partial
35       7036        2028         NaT   -200.0   Ontime
36       7037        2115  2023-08-15      NaN   Missed
37       7038        2038         NaT  15000.0   Missed
38       7039        2098         NaT  15000.0  Partial
39       7040        2069  2022-07-15   -200.0      NaN
40       7041        2037         NaT   -200.0   Ontime
41       7042        2020         NaT  15000.0   Missed
42       7043        2102  2023-08-15   5000.0   Ontime
43       7044        2189         NaT      NaN  Partial
44       7045        2040  2023-08-15   -200.0   Missed
45       7046        2081         NaT   5000.0   Missed
46       7047        2045         NaT      NaN   Missed
47       7048        2161         NaT   -200.0   Ontime
48       7049        2083  2022-07-15   5000.0   Missed
49       7050        2194         NaT      NaN  Partial
50       7051        2049  2023-08-15   5000.0   Ontime
51       7052        2017         NaT      NaN   Ontime
52       7053        2116         NaT   5000.0   Ontime
53       7054        2130  2023-08-15   -200.0   Ontime
54       7055        2198  2023-08-15  15000.0   Ontime
55       7056        2174  2023-08-15   5000.0  Partial
56       7057        2176         NaT  15000.0   Ontime
57       7058        2127  2023-08-15      NaN  Partial
58       7059        2072  2023-08-15  15000.0   Ontime
59       7060        2086  2023-08-15   5000.0      NaN
60       7061        2027  2022-07-15      NaN  Partial
61       7062        2086  2023-08-15  15000.0   Ontime
62       7063        2073  2022-07-15  15000.0   Missed
63       7064        2008  2022-07-15   5000.0   Ontime
64       7065        2041         NaT  15000.0   Ontime
65       7066        2107  2022-07-15   5000.0      NaN
66       7067        2074         NaT      NaN      NaN
67       7068        2198         NaT   -200.0   Ontime
68       7069        2096         NaT      NaN   Ontime
69       7070        2191  2023-08-15      NaN   Ontime
70       7071        2132  2022-07-15   5000.0   Ontime
71       7072        2009         NaT      NaN   Ontime
72       7073        2041         NaT  15000.0   Ontime
73       7074        2141         NaT   -200.0   Missed
74       7075        2109  2022-07-15   -200.0   Ontime
75       7076        2061  2022-07-15  15000.0      NaN
76       7077        2104  2023-08-15   5000.0  Partial
77       7078        2180  2022-07-15   -200.0  Partial
78       7079        2078         NaT      NaN   Ontime
79       7080        2009  2022-07-15   -200.0  Partial
80       7081        2062  2023-08-15  15000.0      NaN
81       7082        2187         NaT   -200.0   Ontime
82       7083        2152         NaT  15000.0  Partial
83       7084        2167  2022-07-15   5000.0   Ontime
84       7085        2182  2023-08-15      NaN  Partial
85       7086        2024         NaT      NaN   Missed
86       7087        2057         NaT   5000.0      NaN
87       7088        2012         NaT   5000.0   Ontime
88       7089        2001         NaT      NaN   Ontime
89       7090        2167         NaT      NaN   Ontime

In [6]:
df["FacilityIDExists"]=df["FacilityID"].isin(df2["FacilityID"])
df

    PaymentID  FacilityID PaymentDate   Amount   Status  FacilityIDExists
0        7001        2176         NaT   5000.0  Partial              True
1        7002        2159  2022-07-15   5000.0   Ontime              True
2        7003        2045         NaT      NaN   Missed             False
3        7004        2167         NaT   5000.0      NaN             False
4        7005        2014  2022-07-15   -200.0   Ontime              True
5        7006        2057         NaT   5000.0   Missed              True
6        7007        2141         NaT  15000.0   Missed             False
7        7008        2061         NaT   5000.0      NaN             False
8        7009        2146         NaT   5000.0   Ontime             False
9        7010        2174  2023-08-15   5000.0   Missed             False
10       7011        2014         NaT   5000.0  Partial              True
11       7012        2005  2023-08-15      NaN   Ontime              True
12       7013        2188         NaT   -200.0      NaN             False
13       7014        2104  2022-07-15  15000.0      NaN             False
14       7015        2101  2022-07-15   -200.0  Partial             False
15       7016        2093         NaT      NaN  Partial              True
16       7017        2087  2023-08-15      NaN  Partial             False
17       7018        2138  2023-08-15      NaN  Partial             False
18       7019        2116         NaT  15000.0      NaN             False
19       7020        2033  2022-07-15   5000.0   Missed              True
20       7021        2125         NaT      NaN   Missed             False
21       7022        2133  2023-08-15  15000.0  Partial              True
22       7023        2023  2022-07-15  15000.0   Ontime              True
23       7024        2075         NaT      NaN      NaN              True
24       7025        2158  2022-07-15      NaN  Partial             False
25       7026        2124  2022-07-15  15000.0  Partial             False
26       7027        2028         NaT      NaN   Ontime              True
27       7028        2008         NaT  15000.0   Ontime             False
28       7029        2116  2022-07-15   5000.0   Missed             False
29       7030        2092         NaT   -200.0  Partial             False
30       7031        2192         NaT   5000.0  Partial              True
31       7032        2104         NaT   5000.0  Partial             False
32       7033        2186  2022-07-15   -200.0      NaN              True
33       7034        2043         NaT   5000.0      NaN             False
34       7035        2090         NaT   -200.0  Partial             False
35       7036        2028         NaT   -200.0   Ontime              True
36       7037        2115  2023-08-15      NaN   Missed              True
37       7038        2038         NaT  15000.0   Missed             False
38       7039        2098         NaT  15000.0  Partial             False
39       7040        2069  2022-07-15   -200.0      NaN             False
40       7041        2037         NaT   -200.0   Ontime              True
41       7042        2020         NaT  15000.0   Missed             False
42       7043        2102  2023-08-15   5000.0   Ontime             False
43       7044        2189         NaT      NaN  Partial             False
44       7045        2040  2023-08-15   -200.0   Missed             False
45       7046        2081         NaT   5000.0   Missed             False
46       7047        2045         NaT      NaN   Missed             False
47       7048        2161         NaT   -200.0   Ontime              True
48       7049        2083  2022-07-15   5000.0   Missed              True
49       7050        2194         NaT      NaN  Partial             False
50       7051        2049  2023-08-15   5000.0   Ontime             False
51       7052        2017         NaT      NaN   Ontime             False
52       7053        2116         NaT   5000.0   Ontime             False
53       7054        2130  2023-08-15   -200.0   Ontime              True
54       7055        2198  2023-08-15  15000.0   Ontime              True
55       7056        2174  2023-08-15   5000.0  Partial             False
56       7057        2176         NaT  15000.0   Ontime              True
57       7058        2127  2023-08-15      NaN  Partial              True
58       7059        2072  2023-08-15  15000.0   Ontime              True
59       7060        2086  2023-08-15   5000.0      NaN              True
60       7061        2027  2022-07-15      NaN  Partial             False
61       7062        2086  2023-08-15  15000.0   Ontime              True
62       7063        2073  2022-07-15  15000.0   Missed             False
63       7064        2008  2022-07-15   5000.0   Ontime             False
64       7065        2041         NaT  15000.0   Ontime             False
65       7066        2107  2022-07-15   5000.0      NaN             False
66       7067        2074         NaT      NaN      NaN             False
67       7068        2198         NaT   -200.0   Ontime              True
68       7069        2096         NaT      NaN   Ontime             False
69       7070        2191  2023-08-15      NaN   Ontime              True
70       7071        2132  2022-07-15   5000.0   Ontime             False
71       7072        2009         NaT      NaN   Ontime             False
72       7073        2041         NaT  15000.0   Ontime             False
73       7074        2141         NaT   -200.0   Missed             False
74       7075        2109  2022-07-15   -200.0   Ontime             False
75       7076        2061  2022-07-15  15000.0      NaN             False
76       7077        2104  2023-08-15   5000.0  Partial             False
77       7078        2180  2022-07-15   -200.0  Partial             False
78       7079        2078         NaT      NaN   Ontime             False
79       7080        2009  2022-07-15   -200.0  Partial             False
80       7081        2062  2023-08-15  15000.0      NaN              True
81       7082        2187         NaT   -200.0   Ontime             False
82       7083        2152         NaT  15000.0  Partial             False
83       7084        2167  2022-07-15   5000.0   Ontime             False
84       7085        2182  2023-08-15      NaN  Partial             False
85       7086        2024         NaT      NaN   Missed              True
86       7087        2057         NaT   5000.0      NaN              True
87       7088        2012         NaT   5000.0   Ontime             False
88       7089        2001         NaT      NaN   Ontime             False
89       7090        2167         NaT      NaN   Ontime             False

In [7]:
df["NegativeValueExists"]=df["Amount"]<0
df

,PaymentID,FacilityID,PaymentDate,Amount,Status,FacilityIDExists,NegativeValueExists
0,7001,2176,NaT,5000.0,Partial,True,False
1,7002,2159,2022-07-15,5000.0,Ontime,True,False
2,7003,2045,NaT,NaN,Missed,False,False
3,7004,2167,NaT,5000.0,NaN,False,False
4,7005,2014,2022-07-15,-200.0,Ontime,True,True
5,7006,2057,NaT,5000.0,Missed,True,False
6,7007,2141,NaT,15000.0,Missed,False,False
7,7008,2061,NaT,5000.0,NaN,False,False
8,7009,2146,NaT,5000.0,Ontime,False,False
9,7010,2174,2023-08-15,5000.0,Missed,False,False
10,7011,2014,NaT,5000.0,Partial,True,False
11,7012,2005,2023-08-15,NaN,Ontime,True,False
12,7013,2188,NaT,-200.0,NaN,False,True
13,7014,2104,2022-07-15,15000.0,NaN,False,False
14,7015,2101,2022-07-15,-200.0,Partial,False,True
15,7016,2093,NaT,NaN,Partial,True,False
16,7017,2087,2023-08-15,NaN,Partial,False,False
17,7018,2138,2023-08-15,NaN,Partial,False,False
18,7019,2116,NaT,15000.0,NaN,False,False
19,7020,2033,2022-07-15,5000.0,Missed,True,False
20,7021,2125,NaT,NaN,Missed,False,False
21,7022,2133,2023-08-15,15000.0,Partial,True,False
22,7023,2023,2022-07-15,15000.0,Ontime,True,False
23,7024,2075,NaT,NaN,NaN,True,False
24,7025,2158,2022-07-15,NaN,Partial,False,False
25,7026,2124,2022-07-15,15000.0,Partial,False,False
26,7027,2028,NaT,NaN,Ontime,True,False
27,7028,2008,NaT,15000.0,Ontime,False,False
28,7029,2116,2022-07-15,5000.0,Missed,False,False
29,7030,2092,NaT,-200.0,Partial,False,True
30,7031,2192,NaT,5000.0,Partial,True,False
31,7032,2104,NaT,5000.0,Partial,False,False
32,7033,2186,2022-07-15,-200.0,NaN,True,True
33,7034,2043,NaT,5000.0,NaN,False,False
34,7035,2090,NaT,-200.0,Partial,False,True
35,7036,2028,NaT,-200.0,Ontime,True,True
36,7037,2115,2023-08-15,NaN,Missed,True,False
37,7038,2038,NaT,15000.0,Missed,False,False
38,7039,2098,NaT,15000.0,Partial,False,False
39,7040,2069,2022-07-15,-200.0,NaN,False,True
40,7041,2037,NaT,-200.0,Ontime,True,True
41,7042,2020,NaT,15000.0,Missed,False,False
42,7043,2102,2023-08-15,5000.0,Ontime,False,False
43,7044,2189,NaT,NaN,Partial,False,False
44,7045,2040,2023-08-15,-200.0,Missed,False,True
45,7046,2081,NaT,5000.0,Missed,False,False
46,7047,2045,NaT,NaN,Missed,False,False
47,7048,2161,NaT,-200.0,Ontime,True,True
48,7049,2083,2022-07-15,5000.0,Missed,True,False
49,7050,2194,NaT,NaN,Partial,False,False
50,7051,2049,2023-08-15,5000.0,Ontime,False,False
51,7052,2017,NaT,NaN,Ontime,False,False
52,7053,2116,NaT,5000.0,Ontime,False,False
53,7054,2130,2023-08-15,-200.0,Ontime,True,True
54,7055,2198,2023-08-15,15000.0,Ontime,True,False
55,7056,2174,2023-08-15,5000.0,Partial,False,False
56,7057,2176,NaT,15000.0,Ontime,True,False
57,7058,2127,2023-08-15,NaN,Partial,True,False
58,7059,2072,2023-08-15,15000.0,Ontime,True,False
59,7060,2086,2023-08-15,5000.0,NaN,True,False
60,7061,2027,2022-07-15,NaN,Partial,False,False
61,7062,2086,2023-08-15,15000.0,Ontime,True,False
62,7063,2073,2022-07-15,15000.0,Missed,False,False
63,7064,2008,2022-07-15,5000.0,Ontime,False,False
64,7065,2041,NaT,15000.0,Ontime,False,False
65,7066,2107,2022-07-15,5000.0,NaN,False,False
66,7067,2074,NaT,NaN,NaN,False,False
67,7068,2198,NaT,-200.0,Ontime,True,True
68,7069,2096,NaT,NaN,Ontime,False,False
69,7070,2191,2023-08-15,NaN,Ontime,True,False
70,7071,2132,2022-07-15,5000.0,Ontime,False,False
71,7072,2009,NaT,NaN,Ontime,False,False
72,7073,2041,NaT,15000.0,Ontime,False,False
73,7074,2141,NaT,-200.0,Missed,False,True
74,7075,2109,2022-07-15,-200.0,Ontime,False,True
75,7076,2061,2022-07-15,15000.0,NaN,False,False
76,7077,2104,2023-08-15,5000.0,Partial,False,False
77,7078,2180,2022-07-15,-200.0,Partial,False,True
78,7079,2078,NaT,NaN,Ontime,False,False
79,7080,2009,2022-07-15,-200.0,Partial,False,True
80,7081,2062,2023-08-15,15000.0,NaN,True,False
81,7082,2187,NaT,-200.0,Ontime,False,True
82,7083,2152,NaT,15000.0,Partial,False,False
83,7084,2167,2022-07-15,5000.0,Ontime,False,False
84,7085,2182,2023-08-15,NaN,Partial,False,False
85,7086,2024,NaT,NaN,Missed,True,False
86,7087,2057,NaT,5000.0,NaN,True,False
87,7088,2012,NaT,5000.0,Ontime,False,False
88,7089,2001,NaT,NaN,Ontime,False,False
89,7090,2167,NaT,NaN,Ontime,False,False

In [8]:
df["PaymentDateMissingOrInvalid"] = df["PaymentDate"].isna()
df["AmountMissing"] = df["Amount"].isna()
df["StatusMissing"] = df["Status"].isna()

In [9]:
PROJECT_DIR = Path.cwd().parent

CLEAN_DIR = PROJECT_DIR / "data" / "Final_Version" / "Clean"
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

output_file = CLEAN_DIR / "Payments_Clean.csv"

df.to_csv(output_file, index=False)

print("Saved successfully:", output_file)
print("Rows saved:", len(df))

Saved successfully: C:\Users\Madhura J\Desktop\Data Analyst Banking Project\data\Final_Version\Clean\Payments_Clean.csv
Rows saved: 90